import { enforceExistingUserSecurity } from '../../shared/functionSecurity.js';
import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

const MANAGE_ROLES = new Set(['super_admin', 'admin', 'manager', 'logistics_manager']);
const DRIVER_ROLES = new Set(['driver', ...MANAGE_ROLES]);
const TERMINAL_STOP = new Set(['completed', 'failed', 'skipped', 'cancelled']);
function canAccessUnit(user: any, unitId?: string) { if (!unitId || ['super_admin', 'admin'].includes(user?.role)) return true; return new Set([user?.primary_unit_id, ...(user?.allowed_unit_ids || [])].filter(Boolean)).has(unitId); }
function isManager(user: any) { return MANAGE_ROLES.has(user?.role) || (user?.permissions || []).includes('logistics.manage'); }
function isDriverFor(user: any, route: any) { return isManager(user) || (DRIVER_ROLES.has(user?.role) && route.driver_user_id === user.id) || (user?.permissions || []).includes('logistics.execute'); }
function geo(value: any) { if (!value || !Number.isFinite(Number(value.latitude)) || !Number.isFinite(Number(value.longitude))) return undefined; return { latitude: Number(value.latitude), longitude: Number(value.longitude), accuracy_meters: Number(value.accuracy_meters || value.accuracy || 0), captured_at: value.captured_at || new Date().toISOString() }; }
function distanceMeters(a: any, b: any) { if (!a || !b || !Number.isFinite(Number(a.latitude)) || !Number.isFinite(Number(b.latitude))) return null; const rad = (v: number) => v * Math.PI / 180; const dLat = rad(Number(b.latitude) - Number(a.latitude)); const dLon = rad(Number(b.longitude) - Number(a.longitude)); const x = Math.sin(dLat / 2) ** 2 + Math.cos(rad(Number(a.latitude))) * Math.cos(rad(Number(b.latitude))) * Math.sin(dLon / 2) ** 2; return Math.round(6371000 * 2 * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x))); }
async function event(base44: any, route: any, user: any, requestId: string, eventType: string, key: string, data: any = {}) { const existing = await base44.asServiceRole.entities.RouteEvent.filter({ idempotency_key: key }, '-occurred_at', 1); if (existing[0]) return existing[0]; return base44.asServiceRole.entities.RouteEvent.create({ unit_id: route.unit_id, route_id: route.id, route_stop_id: data.route_stop_id, pickup_id: data.pickup_id, driver_user_id: route.driver_user_id || user.id, vehicle_id: route.vehicle_id, event_type: eventType, occurred_at: data.occurred_at || new Date().toISOString(), location: geo(data.location), accuracy_meters: Number(data.location?.accuracy_meters || data.location?.accuracy || 0), reason_code: data.reason_code, notes: data.notes, proof_asset_ids: data.proof_asset_ids || [], idempotency_key: key, request_id: requestId, metadata: data.metadata || {} }); }
async function audit(base44: any, route: any, user: any, requestId: string, action: string, reason: string, before?: any) { return base44.asServiceRole.entities.AuditLog.create({ action, entity_type: 'delivery_route', entity_id: route.id, item_label: route.code, reason, user_email: user.email, user_name: user.full_name || user.display_name, user_role: user.role, unit_id: route.unit_id, request_id: requestId, before_data: before, after_data: route, domain: 'logistics', severity: ['complete', 'cancel'].includes(action) ? 'notice' : 'info', result: 'success', occurred_at: new Date().toISOString(), success: true }); }

Deno.serve(async (req) => {
  const requestId = crypto.randomUUID();
  try {
    if (req.method !== 'POST') return Response.json({ error: 'method_not_allowed', request_id: requestId }, { status: 405 });
    const base44 = createClientFromRequest(req); const user = await base44.auth.me();
    await enforceExistingUserSecurity(base44, req, user, { source: 'manage_delivery_route' });
    if (!user) return Response.json({ error: 'authentication_required', request_id: requestId }, { status: 401 });
    const body = await req.json(); const action = String(body.action || 'list'); const now = new Date().toISOString();

    if (action === 'list') {
      const [routes, stops, vehicles] = await Promise.all([base44.asServiceRole.entities.DeliveryRoute.list('-route_date', 3000), base44.asServiceRole.entities.RouteStop.list('sequence', 10000), base44.asServiceRole.entities.FleetVehicle.list('code', 2000)]);
      const visibleRoutes = routes.filter((route: any) => canAccessUnit(user, route.unit_id) && (isManager(user) || route.driver_user_id === user.id || (user.permissions || []).includes('logistics.view')));
      const ids = new Set(visibleRoutes.map((route: any) => route.id));
      return Response.json({ routes: visibleRoutes, stops: stops.filter((stop: any) => ids.has(stop.route_id)), vehicles: vehicles.filter((vehicle: any) => canAccessUnit(user, vehicle.unit_id)), request_id: requestId });
    }

    if (action === 'create_route') {
      if (!isManager(user)) return Response.json({ error: 'management_forbidden', request_id: requestId }, { status: 403 });
      const unitId = body.unit_id || user.primary_unit_id; if (!canAccessUnit(user, unitId)) return Response.json({ error: 'forbidden_unit', request_id: requestId }, { status: 403 });
      const inputStops = Array.isArray(body.stops) ? body.stops : [];
      if (!body.route_date || inputStops.length === 0) return Response.json({ error: 'route_date_and_stops_required', request_id: requestId }, { status: 422 });
      const key = String(body.idempotency_key || `route:${unitId}:${body.route_date}:${crypto.randomUUID()}`); const existing = await base44.asServiceRole.entities.DeliveryRoute.filter({ idempotency_key: key }, '-created_date', 1); if (existing[0]) return Response.json({ route: existing[0], idempotent: true, request_id: requestId });
      const vehicles = body.vehicle_id ? await base44.asServiceRole.entities.FleetVehicle.filter({ id: body.vehicle_id }, '-created_date', 1) : []; const vehicle = vehicles[0] || (body.vehicle_id ? await base44.asServiceRole.entities.FleetVehicle.get(body.vehicle_id).catch(() => null) : null);
      if (vehicle && (!canAccessUnit(user, vehicle.unit_id) || !['available', 'assigned'].includes(vehicle.status))) return Response.json({ error: 'vehicle_not_available', request_id: requestId }, { status: 409 });
      const route = await base44.asServiceRole.entities.DeliveryRoute.create({ unit_id: unitId, code: String(body.code || `R-${String(body.route_date).replaceAll('-', '')}-${Date.now().toString(36).slice(-4)}`).toUpperCase(), route_date: body.route_date, route_type: body.route_type || 'mixed', status: body.driver_user_id && body.vehicle_id ? 'assigned' : 'planned', driver_user_id: body.driver_user_id, driver_name: body.driver_name, vehicle_id: body.vehicle_id, stop_ids: [], planned_stop_count: inputStops.length, completed_stop_count: 0, failed_stop_count: 0, planned_distance_km: Math.max(0, Number(body.planned_distance_km || 0)), planned_duration_minutes: Math.max(0, Number(body.planned_duration_minutes || 0)), planned_load_kg: Math.max(0, Number(body.planned_load_kg || 0)), estimated_cost: vehicle ? Math.max(0, Number(body.planned_distance_km || 0)) * Number(vehicle.cost_per_km || 0) : 0, created_by_user_id: user.id, idempotency_key: key, request_id: requestId, notes: body.notes, metadata: body.metadata || {} });
      const createdStops: any[] = [];
      try {
        for (let index = 0; index < inputStops.length; index++) {
          const input = inputStops[index];
          if (!input.address) throw new Error('stop_address_required');
          const stop = await base44.asServiceRole.entities.RouteStop.create({ unit_id: unitId, route_id: route.id, stop_type: input.stop_type || (input.pickup_id ? 'pickup' : 'delivery'), pickup_id: input.pickup_id, delivery_receipt_id: input.delivery_receipt_id, customer_id: input.customer_id, order_ids: input.order_ids || [], sequence: Number(input.sequence || index + 1), status: 'planned', address: input.address, neighborhood: input.neighborhood, latitude: input.latitude != null ? Number(input.latitude) : undefined, longitude: input.longitude != null ? Number(input.longitude) : undefined, planned_arrival_at: input.planned_arrival_at, confirmation_code_hash: input.confirmation_code_hash, notes: input.notes, idempotency_key: `${key}:stop:${index + 1}`, request_id: requestId, metadata: input.metadata || {} });
          createdStops.push(stop);
          if (input.pickup_id) await base44.asServiceRole.entities.Pickup.update(input.pickup_id, { unit_id: unitId, route_id: route.id, route_stop_id: stop.id, driver_user_id: body.driver_user_id, driver_name: body.driver_name, vehicle_id: body.vehicle_id, sequence: stop.sequence, planned_arrival_at: stop.planned_arrival_at, request_id: requestId });
        }
      } catch (error) { for (const stop of createdStops) await base44.asServiceRole.entities.RouteStop.update(stop.id, { status: 'cancelled', notes: 'Compensação por falha ao criar rota' }); await base44.asServiceRole.entities.DeliveryRoute.update(route.id, { status: 'cancelled', notes: `Falha de criação: ${error.message}` }); throw error; }
      const updated = await base44.asServiceRole.entities.DeliveryRoute.update(route.id, { stop_ids: createdStops.map((stop) => stop.id) }); if (vehicle) await base44.asServiceRole.entities.FleetVehicle.update(vehicle.id, { status: 'assigned', current_driver_user_id: body.driver_user_id, updated_by_user_id: user.id, change_reason: `Atribuído à rota ${updated.code}` });
      await event(base44, updated, user, requestId, 'route_assigned', `${key}:assigned`, { notes: 'Rota criada e atribuída' }); await audit(base44, updated, user, requestId, 'create', String(body.reason || 'Rota planejada com paradas selecionadas'));
      return Response.json({ route: updated, stops: createdStops, request_id: requestId });
    }

    const route = await base44.asServiceRole.entities.DeliveryRoute.get(body.route_id); if (!route || !canAccessUnit(user, route.unit_id)) return Response.json({ error: 'route_not_found', request_id: requestId }, { status: 404 });
    if (!isDriverFor(user, route)) return Response.json({ error: 'route_execution_forbidden', request_id: requestId }, { status: 403 });
    const key = String(body.idempotency_key || `${action}:${route.id}:${crypto.randomUUID()}`);

    if (action === 'start_route') {
      if (!['assigned', 'planned', 'paused'].includes(route.status)) return Response.json({ error: 'invalid_route_state', request_id: requestId }, { status: 409 });
      if (!route.driver_user_id || !route.vehicle_id) return Response.json({ error: 'driver_and_vehicle_required', request_id: requestId }, { status: 422 });
      const vehicle = await base44.asServiceRole.entities.FleetVehicle.get(route.vehicle_id); if (!vehicle || !['available', 'assigned', 'in_route'].includes(vehicle.status)) return Response.json({ error: 'vehicle_not_available', request_id: requestId }, { status: 409 });
      const updated = await base44.asServiceRole.entities.DeliveryRoute.update(route.id, { status: 'in_progress', started_at: route.started_at || now, start_odometer_km: body.odometer_km != null ? Number(body.odometer_km) : route.start_odometer_km, start_location: geo(body.location) || route.start_location }); await base44.asServiceRole.entities.FleetVehicle.update(vehicle.id, { status: 'in_route', current_driver_user_id: route.driver_user_id, odometer_km: Math.max(Number(vehicle.odometer_km || 0), Number(body.odometer_km || 0)), last_location: geo(body.location), last_location_at: now, change_reason: `Rota ${route.code} iniciada` }); await event(base44, updated, user, requestId, route.status === 'paused' ? 'route_resumed' : 'route_started', key, { location: body.location }); return Response.json({ route: updated, request_id: requestId });
    }

    if (action === 'pause_route') {
      if (route.status !== 'in_progress') return Response.json({ error: 'route_not_in_progress', request_id: requestId }, { status: 409 }); const reason = String(body.reason || '').trim(); if (reason.length < 8) return Response.json({ error: 'reason_required', request_id: requestId }, { status: 422 });
      const updated = await base44.asServiceRole.entities.DeliveryRoute.update(route.id, { status: 'paused', paused_at: now, notes: [route.notes, reason].filter(Boolean).join('\n') }); await event(base44, updated, user, requestId, 'route_paused', key, { location: body.location, notes: reason }); return Response.json({ route: updated, request_id: requestId });
    }

    if (action === 'record_location') {
      if (!['in_progress', 'paused'].includes(route.status)) return Response.json({ error: 'route_not_active', request_id: requestId }, { status: 409 }); const location = geo(body.location); if (!location) return Response.json({ error: 'valid_location_required', request_id: requestId }, { status: 422 });
      await event(base44, route, user, requestId, 'location', key, { location }); if (route.vehicle_id) await base44.asServiceRole.entities.FleetVehicle.update(route.vehicle_id, { last_location: location, last_location_at: now }); return Response.json({ recorded: true, location, request_id: requestId });
    }

    const stop = body.route_stop_id ? await base44.asServiceRole.entities.RouteStop.get(body.route_stop_id) : null; if (['arrive_stop', 'start_stop', 'complete_stop', 'fail_stop', 'skip_stop'].includes(action) && (!stop || stop.route_id !== route.id)) return Response.json({ error: 'route_stop_not_found', request_id: requestId }, { status: 404 });

    if (action === 'arrive_stop') {
      if (!['in_progress', 'paused'].includes(route.status) || !['planned', 'en_route'].includes(stop.status)) return Response.json({ error: 'invalid_stop_state', request_id: requestId }, { status: 409 }); const location = geo(body.location); const target = Number.isFinite(Number(stop.latitude)) && Number.isFinite(Number(stop.longitude)) ? { latitude: stop.latitude, longitude: stop.longitude } : null; const distance = distanceMeters(location, target);
      const updated = await base44.asServiceRole.entities.RouteStop.update(stop.id, { status: 'arrived', arrival_at: now, attempt_count: Number(stop.attempt_count || 0) + 1, check_in_location: location, distance_from_target_meters: distance }); await event(base44, route, user, requestId, 'arrived', key, { route_stop_id: stop.id, pickup_id: stop.pickup_id, location }); if (stop.pickup_id) await base44.asServiceRole.entities.Pickup.update(stop.pickup_id, { arrival_at: now, attempt_count: updated.attempt_count, geo_check_in: location, last_location: location }); return Response.json({ stop: updated, distance_from_target_meters: distance, request_id: requestId });
    }

    if (action === 'start_stop') {
      if (stop.status !== 'arrived') return Response.json({ error: 'stop_not_arrived', request_id: requestId }, { status: 409 }); const updated = await base44.asServiceRole.entities.RouteStop.update(stop.id, { status: 'servicing', service_started_at: now }); await event(base44, route, user, requestId, 'service_started', key, { route_stop_id: stop.id, pickup_id: stop.pickup_id, location: body.location }); if (stop.pickup_id) await base44.asServiceRole.entities.Pickup.update(stop.pickup_id, { service_started_at: now }); return Response.json({ stop: updated, request_id: requestId });
    }

    if (action === 'complete_stop') {
      if (!['arrived', 'servicing'].includes(stop.status)) return Response.json({ error: 'stop_not_ready_for_completion', request_id: requestId }, { status: 409 }); if (stop.confirmation_code_hash && String(body.confirmation_code_hash || '') !== stop.confirmation_code_hash) return Response.json({ error: 'invalid_confirmation_code', request_id: requestId }, { status: 422 });
      const location = geo(body.location); const duration = stop.service_started_at ? Math.max(0, Math.round((Date.now() - new Date(stop.service_started_at).getTime()) / 60000)) : 0; const updated = await base44.asServiceRole.entities.RouteStop.update(stop.id, { status: 'completed', completed_at: now, recipient_name: body.recipient_name, recipient_document_last4: String(body.recipient_document || '').replace(/\D/g, '').slice(-4) || body.recipient_document_last4, proof_asset_ids: body.proof_asset_ids || [], signature_asset_id: body.signature_asset_id, check_out_location: location, duration_minutes: duration, notes: body.notes || stop.notes }); await event(base44, route, user, requestId, 'stop_completed', key, { route_stop_id: stop.id, pickup_id: stop.pickup_id, location, proof_asset_ids: updated.proof_asset_ids }); if (stop.pickup_id) await base44.asServiceRole.entities.Pickup.update(stop.pickup_id, { status: 'completed', completed_at: now, recipient_name: updated.recipient_name, recipient_document_last4: updated.recipient_document_last4, proof_asset_ids: updated.proof_asset_ids, signature_asset_id: updated.signature_asset_id, geo_check_out: location, duration_minutes: duration }); const completedCount = (await base44.asServiceRole.entities.RouteStop.filter({ route_id: route.id, status: 'completed' }, 'sequence', 1000)).length; const refreshed = await base44.asServiceRole.entities.DeliveryRoute.update(route.id, { completed_stop_count: completedCount }); return Response.json({ route: refreshed, stop: updated, request_id: requestId });
    }

    if (action === 'fail_stop' || action === 'skip_stop') {
      const reason = String(body.reason_code || '').trim(); const notes = String(body.notes || '').trim(); if (!reason || notes.length < 8) return Response.json({ error: 'failure_reason_and_notes_required', request_id: requestId }, { status: 422 });
      const status = action === 'skip_stop' ? 'skipped' : 'failed'; const updated = await base44.asServiceRole.entities.RouteStop.update(stop.id, { status, completed_at: now, failure_reason_code: reason, failure_notes: notes, check_out_location: geo(body.location), proof_asset_ids: body.proof_asset_ids || [] }); await event(base44, route, user, requestId, action === 'skip_stop' ? 'stop_skipped' : 'stop_failed', key, { route_stop_id: stop.id, pickup_id: stop.pickup_id, location: body.location, reason_code: reason, notes, proof_asset_ids: updated.proof_asset_ids }); if (stop.pickup_id) await base44.asServiceRole.entities.Pickup.update(stop.pickup_id, { status: 'missed', completed_at: now, failure_reason_code: reason, failure_notes: notes, proof_asset_ids: updated.proof_asset_ids, geo_check_out: geo(body.location) }); const failedCount = (await base44.asServiceRole.entities.RouteStop.filter({ route_id: route.id, status }, 'sequence', 1000)).length; const refreshed = await base44.asServiceRole.entities.DeliveryRoute.update(route.id, { failed_stop_count: failedCount }); return Response.json({ route: refreshed, stop: updated, request_id: requestId });
    }

    if (action === 'complete_route') {
      const stops = await base44.asServiceRole.entities.RouteStop.filter({ route_id: route.id }, 'sequence', 2000); const pending = stops.filter((item: any) => !TERMINAL_STOP.has(item.status)); if (pending.length) return Response.json({ error: 'route_has_pending_stops', pending_stop_ids: pending.map((item: any) => item.id), request_id: requestId }, { status: 409 });
      const endOdometer = body.odometer_km != null ? Number(body.odometer_km) : undefined; if (endOdometer != null && route.start_odometer_km != null && endOdometer < Number(route.start_odometer_km)) return Response.json({ error: 'invalid_odometer', request_id: requestId }, { status: 422 }); const distance = endOdometer != null && route.start_odometer_km != null ? endOdometer - Number(route.start_odometer_km) : number(route.planned_distance_km); const vehicle = route.vehicle_id ? await base44.asServiceRole.entities.FleetVehicle.get(route.vehicle_id) : null;
      const updated = await base44.asServiceRole.entities.DeliveryRoute.update(route.id, { status: 'completed', completed_at: now, completed_stop_count: stops.filter((item: any) => item.status === 'completed').length, failed_stop_count: stops.filter((item: any) => ['failed', 'skipped'].includes(item.status)).length, actual_distance_km: Math.max(0, distance), actual_duration_minutes: route.started_at ? Math.max(0, Math.round((Date.now() - new Date(route.started_at).getTime()) / 60000)) : 0, actual_cost: Math.max(0, distance) * Number(vehicle?.cost_per_km || 0), end_odometer_km: endOdometer, end_location: geo(body.location), closed_by_user_id: user.id }); if (vehicle) await base44.asServiceRole.entities.FleetVehicle.update(vehicle.id, { status: 'available', current_driver_user_id: undefined, odometer_km: Math.max(Number(vehicle.odometer_km || 0), Number(endOdometer || 0)), last_location: geo(body.location), last_location_at: now, change_reason: `Rota ${route.code} concluída` }); await event(base44, updated, user, requestId, 'route_completed', key, { location: body.location }); await audit(base44, updated, user, requestId, 'complete', String(body.reason || 'Rota concluída após tratamento de todas as paradas'), route); return Response.json({ route: updated, request_id: requestId });
    }

    return Response.json({ error: 'unsupported_action', request_id: requestId }, { status: 422 });
  } catch (error: any) { return Response.json({ error: error?.message || 'delivery_route_failed', request_id: requestId }, { status: ['stop_address_required'].includes(error?.message) ? 422 : 500 }); }
});
