import React, { useEffect, useMemo, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { BarChart, Bar, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, Boxes, Building2, CalendarClock, CircleDollarSign, ClipboardList, Download, Factory, FileJson, FileText, HandCoins, Loader2, PackageSearch, RefreshCcw, Scale, Truck, Users } from 'lucide-react';
import { toast } from 'sonner';
import useUnitAccess from '@/components/units/useUnitAccess';

/** @type {Array<[string, string, import('react').ComponentType<any>]>} */
const REPORTS = [
  ['production', 'Produção', Factory], ['delays', 'Atrasos', CalendarClock], ['rework', 'Retrabalho', RefreshCcw],
  ['third_parties', 'Terceiros', Building2], ['stock', 'Estoque', Boxes], ['consumption', 'Consumo', PackageSearch],
  ['service_margin', 'Margem por serviço', Scale], ['employee_productivity', 'Produtividade', Users], ['cash', 'Caixa', CircleDollarSign],
  ['billing', 'Faturados', HandCoins], ['fiscal', 'Fiscal', FileText], ['logistics', 'Coleta e entrega', Truck], ['unit_profitability', 'Rentabilidade', Activity],
];
const LABELS = {
  batches: 'Lotes', completed_batches: 'Lotes concluídos', pieces: 'Peças', weight_kg: 'Peso (kg)', actual_cost: 'Custo real', average_cycle_minutes: 'Ciclo médio (min)', average_capacity_percent: 'Capacidade média', completion_rate_percent: 'Conclusão', overdue_items: 'Atrasos', critical_over_7_days: 'Críticos > 7 dias', average_days_late: 'Atraso médio (dias)', maximum_days_late: 'Maior atraso (dias)', cases: 'Casos', completed: 'Concluídos', open: 'Em aberto', rework_rate_percent: 'Taxa de retrabalho', average_resolution_hours: 'Resolução média (h)', jobs: 'Ordens', cost_variance: 'Variação de custo', delayed_jobs: 'Atrasadas', active_items: 'Itens ativos', inventory_value: 'Valor em estoque', low_stock_items: 'Estoque baixo', expiring_lots_30d: 'Lotes a vencer', losses_in_period: 'Perdas', adjustments_in_period: 'Ajustes', movements: 'Movimentos', consumed_quantity: 'Quantidade consumida', consumption_cost: 'Custo de consumo', loss_quantity: 'Quantidade perdida', loss_cost: 'Custo de perdas', loss_percent_of_cost: '% de perdas', services: 'Serviços', revenue: 'Receita', direct_cost: 'Custo direto', contribution_margin: 'Margem', contribution_margin_percent: 'Margem %', negative_margin_services: 'Serviços negativos', employees: 'Funcionários', labor_hours: 'Horas trabalhadas', labor_cost: 'Custo de mão de obra', average_pieces_per_hour: 'Peças/hora', rework_hours: 'Horas de retrabalho', sessions: 'Sessões', closed_sessions: 'Caixas fechados', income: 'Entradas', supplies: 'Suprimentos', withdrawals: 'Sangrias', refunds: 'Estornos', difference: 'Diferença', pending_reconciliation: 'A conciliar', movement_count: 'Movimentos', statements: 'Demonstrativos', issued_amount: 'Faturado', paid_amount: 'Recebido', open_amount: 'Em aberto', overdue_amount: 'Vencido', overdue_statements: 'Títulos vencidos', collection_rate_percent: 'Recebimento %', receivables_in_period: 'Contas no período', documents: 'Documentos', total_amount: 'Valor total', authorized: 'Autorizados', ready_or_draft: 'Preparados', rejected_or_error: 'Rejeitados/erro', cancelled: 'Cancelados', iss_amount: 'ISS', pickups: 'Coletas', completed_pickups: 'Coletas concluídas', missed_pickups: 'Coletas frustradas', pickup_completion_rate_percent: 'Conclusão de coletas', deliveries: 'Entregas', delivered_pieces: 'Peças entregues', delivery_value: 'Valor entregue', partial_deliveries: 'Entregas parciais', units: 'Unidades', total_cost: 'Custo total', profit: 'Resultado', margin_percent: 'Margem %', profitable_units: 'Unidades positivas', negative_units: 'Unidades negativas', actual_material_cost: 'Custo material', actual_labor_cost: 'Custo mão de obra', actual_minutes: 'Minutos reais', planned_minutes: 'Minutos previstos', capacity_percent: 'Capacidade %', margin: 'Margem', pieces_per_hour: 'Peças/hora', average_price: 'Preço médio', overdue: 'Vencido', delayed: 'Atrasado'
};
const MONEY_KEYS = new Set(['actual_cost', 'losses_in_period', 'inventory_value', 'consumption_cost', 'loss_cost', 'revenue', 'direct_cost', 'contribution_margin', 'labor_cost', 'income', 'supplies', 'withdrawals', 'refunds', 'difference', 'pending_reconciliation', 'issued_amount', 'paid_amount', 'open_amount', 'overdue_amount', 'total_amount', 'iss_amount', 'delivery_value', 'total_cost', 'profit', 'cost_variance', 'actual_material_cost', 'actual_labor_cost', 'estimated_cost', 'actual_cost', 'unit_cost', 'total_cost', 'margin', 'average_price', 'opening_amount', 'expected_cash_amount', 'counted_cash_amount', 'third_party_cost', 'production_cost', 'operating_expense', 'revenue_per_garment']);
const PERCENT_KEYS = new Set(['completion_rate_percent', 'average_capacity_percent', 'rework_rate_percent', 'loss_percent_of_cost', 'contribution_margin_percent', 'collection_rate_percent', 'pickup_completion_rate_percent', 'margin_percent', 'rework_percent']);

export default function SpecializedReportsPanel() {
  const { accessibleUnits = [], selectedUnitId } = useUnitAccess();
  const [reportType, setReportType] = useState('production');
  const [startDate, setStartDate] = useState(() => toDateInput(new Date(Date.now() - 29 * 86400000)));
  const [endDate, setEndDate] = useState(() => toDateInput(new Date()));
  const [unitId, setUnitId] = useState(selectedUnitId && selectedUnitId !== 'all' ? selectedUnitId : 'all');
  const [compare, setCompare] = useState(true);
  const [report, setReport] = useState(null);
  const [previous, setPrevious] = useState(null);
  const [loading, setLoading] = useState(false);
  const [activeBreakdown, setActiveBreakdown] = useState(0);

  const load = async () => {
    setLoading(true);
    try {
      const payload = { report_type: reportType, start_date: startDate, end_date: endDate, unit_ids: unitId === 'all' ? [] : [unitId], limit: 1000 };
      const currentRequest = base44.functions.invoke('generate_specialized_report', payload);
      let previousRequest = Promise.resolve(null);
      if (compare) {
        const start = new Date(`${startDate}T00:00:00`); const end = new Date(`${endDate}T00:00:00`); const duration = end.getTime() - start.getTime() + 86400000;
        previousRequest = base44.functions.invoke('generate_specialized_report', { ...payload, start_date: toDateInput(new Date(start.getTime() - duration)), end_date: toDateInput(new Date(start.getTime() - 86400000)) });
      }
      const [currentResponse, previousResponse] = await Promise.all([currentRequest, previousRequest]);
      setReport(currentResponse.data.report); setPrevious(previousResponse?.data?.report || null); setActiveBreakdown(0);
    } catch (error) { console.error(error); toast.error(error?.response?.data?.error || 'Não foi possível gerar o relatório.'); }
    finally { setLoading(false); }
  };

  useEffect(() => { load(); }, [reportType]);

  const cards = useMemo(() => report ? Object.entries(report.summary || {}).slice(0, 8) : [], [report]);
  const breakdown = report?.breakdowns?.[activeBreakdown];
  const columns = useMemo(() => report?.rows?.length ? Object.keys(report.rows[0]).filter((key) => !['metadata', 'payment_summary'].includes(key)).slice(0, 10) : [], [report]);

  const exportCsv = () => {
    if (!report?.rows?.length) return toast.error('Não há linhas para exportar.');
    const keys = Object.keys(report.rows[0]).filter((key) => !['metadata', 'payment_summary'].includes(key));
    const escape = (value) => `"${String(value ?? '').replaceAll('"', '""')}"`;
    const csv = `\uFEFF${[keys.join(';'), ...report.rows.map((row) => keys.map((key) => escape(typeof row[key] === 'object' ? JSON.stringify(row[key]) : row[key])).join(';'))].join('\n')}`;
    downloadBlob(new Blob([csv], { type: 'text/csv;charset=utf-8' }), `relatorio-${reportType}-${startDate}-${endDate}.csv`);
  };
  const exportJson = () => { if (!report) return; downloadBlob(new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' }), `relatorio-${reportType}-${startDate}-${endDate}.json`); };

  const reportConfig = REPORTS.find(([key]) => key === reportType);
  const ReportIcon = reportConfig?.[2] || ClipboardList;
  return <div className="space-y-6">
    <div className="rounded-3xl border border-violet-400/15 bg-gradient-to-br from-violet-500/15 via-white/[0.025] to-orange-500/8 p-5"><div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div><p className="text-xs uppercase tracking-[0.18em] text-violet-300">Analytics operacional</p><h2 className="mt-1 flex items-center gap-2 text-2xl font-bold text-white"><ReportIcon className="h-6 w-6 text-orange-400" />Relatórios especializados</h2><p className="mt-2 max-w-3xl text-sm text-white/45">Treze visões com regras de cálculo documentadas, escopo por unidade, comparação de período e dados detalhados exportáveis.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={exportCsv} disabled={!report?.rows?.length} className="border-white/10 bg-white/5"><Download className="mr-2 h-4 w-4" />CSV</Button><Button variant="outline" onClick={exportJson} disabled={!report} className="border-white/10 bg-white/5"><FileJson className="mr-2 h-4 w-4" />JSON</Button></div></div></div>
    <Card className="border-white/10 bg-white/5 text-white"><CardContent className="grid gap-4 pt-6 md:grid-cols-2 xl:grid-cols-[1.3fr_1fr_1fr_1fr_auto]"><Field label="Relatório"><Select value={reportType} onValueChange={setReportType}><SelectTrigger className="border-white/10 bg-black/20"><SelectValue /></SelectTrigger><SelectContent>{REPORTS.map(([key, label]) => <SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select></Field><Field label="Início"><Input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} className="border-white/10 bg-black/20" /></Field><Field label="Fim"><Input type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} className="border-white/10 bg-black/20" /></Field><Field label="Unidade"><Select value={unitId} onValueChange={setUnitId}><SelectTrigger className="border-white/10 bg-black/20"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Todas permitidas</SelectItem>{accessibleUnits.map((unit) => <SelectItem key={unit.id} value={unit.id}>{unit.name}</SelectItem>)}</SelectContent></Select></Field><div className="flex items-end gap-3"><label className="mb-2 flex items-center gap-2 whitespace-nowrap text-sm text-white/50"><input type="checkbox" checked={compare} onChange={(event) => setCompare(event.target.checked)} className="accent-orange-500" />Comparar</label><Button onClick={load} disabled={loading} className="bg-orange-500 hover:bg-orange-400">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Gerar'}</Button></div></CardContent></Card>
    {loading && !report ? <div className="flex items-center justify-center py-20 text-white/40"><Loader2 className="mr-2 h-5 w-5 animate-spin" />Calculando relatório...</div> : report && <>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([key, value]) => <SummaryCard key={key} name={key} value={value} previous={previous?.summary?.[key]} />)}</div>
      <div className="grid gap-4 xl:grid-cols-2"><Card className="border-white/10 bg-white/[0.035] text-white"><CardHeader><CardTitle>Evolução no período</CardTitle><CardDescription className="text-white/35">Série calculada a partir dos registros do relatório.</CardDescription></CardHeader><CardContent>{report.series?.length ? <ResponsiveContainer width="100%" height={290}><LineChart data={report.series}><CartesianGrid strokeDasharray="3 3" stroke="#ffffff12" /><XAxis dataKey="date" tick={{ fill: '#ffffff66', fontSize: 11 }} /><YAxis tick={{ fill: '#ffffff66', fontSize: 11 }} /><Tooltip contentStyle={{ background: '#241239', border: '1px solid #ffffff20', borderRadius: 12 }} /><Line type="monotone" dataKey="value" stroke="#FF6600" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer> : <Empty text="Este relatório é uma fotografia do período e não possui série temporal." />}</CardContent></Card><Card className="border-white/10 bg-white/[0.035] text-white"><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>Distribuição</CardTitle><CardDescription className="text-white/35">Detalhamento principal do relatório.</CardDescription></div>{report.breakdowns?.length > 1 && <Select value={String(activeBreakdown)} onValueChange={(value) => setActiveBreakdown(Number(value))}><SelectTrigger className="w-56 border-white/10 bg-black/20"><SelectValue /></SelectTrigger><SelectContent>{report.breakdowns.map((item, index) => <SelectItem key={item.key} value={String(index)}>{item.label}</SelectItem>)}</SelectContent></Select>}</div></CardHeader><CardContent>{breakdown?.items?.length ? <ResponsiveContainer width="100%" height={290}><BarChart data={breakdown.items.slice(0, 15)} layout="vertical" margin={{ left: 10 }}><CartesianGrid strokeDasharray="3 3" stroke="#ffffff12" /><XAxis type="number" tick={{ fill: '#ffffff66', fontSize: 11 }} /><YAxis type="category" dataKey="label" width={110} tick={{ fill: '#ffffff99', fontSize: 11 }} /><Tooltip contentStyle={{ background: '#241239', border: '1px solid #ffffff20', borderRadius: 12 }} /><Bar dataKey="value" fill="#7C3AED" radius={[0, 6, 6, 0]} /></BarChart></ResponsiveContainer> : <Empty text="Sem distribuição para o período." />}</CardContent></Card></div>
      <Card className="border-white/10 bg-white/[0.035] text-white"><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>Dados detalhados</CardTitle><CardDescription className="text-white/35">{report.rows?.length || 0} linhas retornadas · geração {new Date(report.generated_at).toLocaleString('pt-BR')}</CardDescription></div><Badge variant="outline" className="border-cyan-500/20 text-cyan-300">{report.data_quality?.rows_considered || 0} registros considerados</Badge></div></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b border-white/10">{columns.map((key) => <th key={key} className="px-3 py-3 text-xs font-medium uppercase tracking-wide text-white/35">{LABELS[key] || humanize(key)}</th>)}</tr></thead><tbody>{report.rows?.slice(0, 300).map((row, index) => <tr key={row.id || index} className="border-b border-white/5 hover:bg-white/[0.025]">{columns.map((key) => <td key={key} className="max-w-[260px] truncate px-3 py-3 text-white/70" title={String(row[key] ?? '')}>{formatValue(key, row[key])}</td>)}</tr>)}</tbody></table>{!report.rows?.length && <Empty text="Nenhum registro detalhado no período." />}</div></CardContent></Card>
      <Card className="border-white/10 bg-white/[0.025] text-white"><CardHeader><CardTitle className="text-base">Definições e qualidade dos dados</CardTitle></CardHeader><CardContent className="grid gap-4 lg:grid-cols-2"><div className="space-y-2">{(report.definitions || []).map((text, index) => <p key={index} className="rounded-xl border border-white/8 bg-black/10 p-3 text-sm text-white/50">{text}</p>)}</div><div className="space-y-2">{(report.data_quality?.limitations || []).length ? report.data_quality.limitations.map((text, index) => <p key={index} className="rounded-xl border border-amber-400/15 bg-amber-500/5 p-3 text-sm text-amber-100/70">{text}</p>) : <p className="rounded-xl border border-emerald-400/15 bg-emerald-500/5 p-3 text-sm text-emerald-100/70">Nenhuma limitação adicional detectada nesta geração.</p>}</div></CardContent></Card>
    </>}
  </div>;
}

function SummaryCard({ name, value, previous }) { const numeric = typeof value === 'number'; const delta = numeric && typeof previous === 'number' ? value - previous : null; return <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-4"><p className="text-xs text-white/35">{LABELS[name] || humanize(name)}</p><div className="mt-2 flex items-end justify-between gap-2"><p className="text-xl font-bold text-white">{formatValue(name, value)}</p>{delta != null && <span className={`text-xs ${delta > 0 ? 'text-emerald-300' : delta < 0 ? 'text-red-300' : 'text-white/35'}`}>{delta > 0 ? '+' : ''}{formatValue(name, delta)}</span>}</div></div>; }
function Field({ label, children }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function Empty({ text }) { return <div className="flex h-[260px] items-center justify-center rounded-xl border border-dashed border-white/10 text-sm text-white/35">{text}</div>; }
function humanize(value) { return String(value || '').replaceAll('_', ' ').replace(/^./, (letter) => letter.toUpperCase()); }
function formatValue(key, value) { if (value == null || value === '') return '—'; if (MONEY_KEYS.has(key)) return Number(value).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }); if (PERCENT_KEYS.has(key)) return `${Number(value).toLocaleString('pt-BR', { maximumFractionDigits: 2 })}%`; if (typeof value === 'number') return value.toLocaleString('pt-BR', { maximumFractionDigits: 2 }); if (typeof value === 'boolean') return value ? 'Sim' : 'Não'; if (typeof value === 'object') return JSON.stringify(value); if (/(_at|_date)$/.test(key) && !Number.isNaN(new Date(value).getTime())) return new Date(value).toLocaleString('pt-BR'); return String(value); }
function toDateInput(date) { return date.toISOString().slice(0, 10); }
function downloadBlob(blob, filename) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); }
