export const REPORT_DATASETS = Object.freeze({
  accounts_receivable:{entity:'AccountsReceivable',category:'financial',date:'due_date',fields:['receivable_number','business_party_id','unit_id','cost_center_id','competence','due_date','original_amount','paid_amount','open_amount','status','collection_status']},
  accounts_payable:{entity:'AccountsPayable',category:'financial',date:'due_date',fields:['payable_number','supplier_id','unit_id','cost_center_id','competence','due_date','original_amount','paid_amount','open_amount','status','category']},
  financial_projections:{entity:'FinancialProjection',category:'financial',date:'period_start',fields:['name','scenario','period_start','period_end','projected_inflows','projected_outflows','projected_balance','status']},
  business_contracts:{entity:'BusinessContract',category:'sales',date:'starts_on',fields:['contract_number','business_party_id','contract_type','starts_on','ends_on','billing_cycle','status','estimated_monthly_amount']},
  sales_opportunities:{entity:'SalesOpportunity',category:'crm',date:'created_date',fields:['opportunity_number','business_party_id','stage','source','owner_user_id','estimated_value','probability','next_action_at','loss_reason']},
  purchase_orders:{entity:'PurchaseOrder',category:'procurement',date:'order_date',fields:['purchase_order_number','supplier_id','cost_center_id','warehouse_id','order_date','expected_delivery_date','total_amount','status','approval_status']},
  stock_items:{entity:'StockItem',category:'inventory',date:'updated_date',fields:['item_code','name','category','unit_of_measure','warehouse_id','current_stock','minimum_stock','average_cost','status']},
  hospital_measurements:{entity:'HospitalBillingMeasurement',category:'hospital',date:'period_start',fields:['measurement_number','business_party_id','business_contract_id','period_start','period_end','total_net_weight','total_piece_count','total_amount','status']},
  weighing_records:{entity:'WeighingRecord',category:'hospital',date:'weighed_at',fields:['weighing_number','business_party_id','hospital_pickup_id','classification','gross_weight','tare_weight','net_weight','weighed_at','status']},
  linen_assets:{entity:'LinenAsset',category:'linen',date:'updated_date',fields:['asset_code','linen_catalog_item_id','business_party_id','ownership_type','quantity','wash_count','condition','status','replacement_cost']},
  linen_losses:{entity:'LinenLossCharge',category:'linen',date:'created_date',fields:['charge_number','business_party_id','business_contract_id','quantity','unit_replacement_cost','total_amount','status']},
  cleaning_measurements:{entity:'ServiceMeasurement',category:'cleaning',date:'period_start',fields:['measurement_number','business_party_id','business_contract_id','cleaning_site_id','period_start','period_end','planned_post_shifts','covered_post_shifts','uncovered_post_shifts','average_quality_score','total_amount','status']},
  cleaning_inspections:{entity:'CleaningInspection',category:'cleaning',date:'completed_at',fields:['inspection_number','cleaning_site_id','inspection_type','completed_at','score','passed','status']},
  conversations:{entity:'Conversation',category:'service',date:'last_message_at',fields:['business_party_id','customer_id','channel','assigned_queue','assigned_user_id','service_mode','priority','status','last_message_at','first_human_response_at','resolved_at']}
});
export function datasetContract(name){const c=REPORT_DATASETS[name];if(!c)throw new Error('report_dataset_not_allowed');return c;}
export function sanitizeColumns(dataset,columns=[]){const c=datasetContract(dataset);const requested=columns.map((x)=>typeof x==='string'?x:x?.field).filter(Boolean);const safe=(requested.length?requested:c.fields).filter((field)=>c.fields.includes(field));if(!safe.length)throw new Error('report_columns_required');return [...new Set(safe)];}
export function applyReportFilters(rows=[],dataset,filters=[]){const c=datasetContract(dataset);return rows.filter((row)=>filters.every((filter)=>{const field=String(filter?.field||'');if(!c.fields.includes(field)&&field!==c.date)return false;const value=row?.[field];const target=filter?.value;switch(filter?.operator){case'eq':return String(value??'')===String(target??'');case'neq':return String(value??'')!==String(target??'');case'contains':return String(value??'').toLowerCase().includes(String(target??'').toLowerCase());case'gte':return Number(value)>=Number(target);case'lte':return Number(value)<=Number(target);case'date_from':return new Date(value).getTime()>=new Date(target).getTime();case'date_to':return new Date(value).getTime()<=new Date(target).getTime();case'in':return Array.isArray(target)&&target.map(String).includes(String(value));default:return true;}}));}
export function projectRows(rows,columns){return rows.map((row)=>Object.fromEntries(columns.map((field)=>[field,row?.[field]??null])));}
export function aggregateMetrics(rows=[],metrics=[]){const out={count:rows.length};for(const metric of metrics){const field=String(metric?.field||'');const values=rows.map((row)=>Number(row?.[field])).filter(Number.isFinite);if(metric?.operation==='sum')out[metric.name||`sum_${field}`]=values.reduce((a,b)=>a+b,0);if(metric?.operation==='avg')out[metric.name||`avg_${field}`]=values.length?values.reduce((a,b)=>a+b,0)/values.length:0;if(metric?.operation==='min')out[metric.name||`min_${field}`]=values.length?Math.min(...values):0;if(metric?.operation==='max')out[metric.name||`max_${field}`]=values.length?Math.max(...values):0;}return out;}
export function toCsv(rows=[],columns=[]){const cell=(value)=>`"${String(value??'').replace(/"/g,'""')}"`;return [columns.map(cell).join(','),...rows.map((row)=>columns.map((field)=>cell(row[field])).join(','))].join('\n');}
