export function rounded(value, digits = 3) { const number = Number(value || 0); if (!Number.isFinite(number)) throw new Error('invalid_number'); const factor = 10 ** digits; return Math.round(number * factor) / factor; }
export function money(value) { return rounded(value, 2); }
export function netWeight(gross, tare) { const grossValue = rounded(gross); const tareValue = rounded(tare); if (grossValue <= 0 || tareValue < 0 || tareValue >= grossValue) throw new Error('invalid_weighing'); return rounded(grossValue - tareValue); }
export function processingLotTransition(current, action) { const map = { queue: { classified: 'queued' }, start_wash: { queued: 'washing' }, start_dry: { washing: 'drying' }, start_finish: { drying: 'finishing' }, submit_quality: { finishing: 'quality' }, approve_quality: { quality: 'approved' }, reject_quality: { quality: 'rework' }, restart: { rework: 'washing' }, release_expedition: { approved: 'expedition' }, deliver: { expedition: 'delivered' }, quarantine: { classified: 'quarantine', queued: 'quarantine', washing: 'quarantine', drying: 'quarantine', finishing: 'quarantine', quality: 'quarantine' }, cancel: { classified: 'cancelled', queued: 'cancelled' } }; const next = map[action]?.[current]; if (!next) throw new Error('invalid_processing_lot_transition'); return next; }
export function linenStatusForMovement(current, movementType) { const map = { acquisition: 'available', delivery: 'delivered', customer_use: 'in_use', pickup: 'awaiting_pickup', soiled_entry: 'soiled', processing_entry: 'in_processing', clean_output: 'clean', warehouse_return: 'available', damage: 'damaged', loss: 'lost', recovery: 'available', inventory_adjustment: current, retirement: 'retired', reversal: current }; const next = map[movementType]; if (!next) throw new Error('invalid_linen_movement'); return next; }
export function computeLinenInventoryLine({ expected, counted, damaged = 0, replacementCost = 0 }) { const expectedQuantity = rounded(expected, 0); const countedQuantity = rounded(counted, 0); const damagedQuantity = rounded(damaged, 0); if ([expectedQuantity, countedQuantity, damagedQuantity].some((value) => value < 0) || damagedQuantity > countedQuantity) throw new Error('invalid_linen_inventory_quantities'); const missing = Math.max(0, expectedQuantity - countedQuantity); const divergence = countedQuantity - expectedQuantity; return { expected_quantity: expectedQuantity, counted_quantity: countedQuantity, damaged_quantity: damagedQuantity, lost_quantity: missing, divergence_quantity: divergence, replacement_cost: money(replacementCost), divergence_amount: money((missing + damagedQuantity) * Number(replacementCost || 0)) }; }
export function expectedRemainingWashes(washCount, expectedLifetime) { const lifetime = Math.max(0, Math.round(Number(expectedLifetime || 0))); const used = Math.max(0, Math.round(Number(washCount || 0))); return Math.max(0, lifetime - used); }
export function calculateHospitalMeasurement({ lots = [], conferences = [], priceItems = [], adjustmentAmount = 0, lossChargeAmount = 0 }) { const incoming = rounded(lots.reduce((sum, lot) => sum + Number(lot.incoming_weight_kg || 0), 0)); const clean = rounded(lots.reduce((sum, lot) => sum + Number(lot.clean_weight_kg || 0), 0)); const loss = rounded(lots.reduce((sum, lot) => sum + Number(lot.loss_weight_kg || 0), 0)); const deliveredPieces = Math.round(conferences.reduce((sum, row) => sum + Number(row.accepted_piece_count || 0), 0)); const kgPrice = priceItems.find((item) => item.billing_unit === 'kg' && item.status === 'active'); const piecePrice = priceItems.find((item) => item.billing_unit === 'piece' && item.status === 'active'); let serviceAmount = 0; const details = [];
  if (kgPrice) { const included = Number(kgPrice.included_quantity || 0); const baseQty = Math.max(0, incoming - included); const unitPrice = Number(kgPrice.excess_unit_price ?? kgPrice.unit_price ?? 0); const amount = Math.max(Number(kgPrice.minimum_charge || 0), baseQty * unitPrice); serviceAmount += amount; details.push({ billing_unit: 'kg', quantity: incoming, included_quantity: included, billable_quantity: baseQty, unit_price: unitPrice, amount: money(amount), price_item_id: kgPrice.id }); }
  if (piecePrice && deliveredPieces > 0) { const included = Number(piecePrice.included_quantity || 0); const baseQty = Math.max(0, deliveredPieces - included); const unitPrice = Number(piecePrice.excess_unit_price ?? piecePrice.unit_price ?? 0); const amount = Math.max(Number(piecePrice.minimum_charge || 0), baseQty * unitPrice); serviceAmount += amount; details.push({ billing_unit: 'piece', quantity: deliveredPieces, included_quantity: included, billable_quantity: baseQty, unit_price: unitPrice, amount: money(amount), price_item_id: piecePrice.id }); }
  if (!kgPrice && !piecePrice) throw new Error('active_hospital_price_required'); const adjustments = money(adjustmentAmount); const lossCharges = money(lossChargeAmount); return { incoming_weight_kg: incoming, billable_weight_kg: incoming, clean_weight_kg: clean, loss_weight_kg: loss, piece_count: deliveredPieces, service_amount: money(serviceAmount), loss_charge_amount: lossCharges, adjustment_amount: adjustments, total_amount: money(serviceAmount + lossCharges + adjustments), calculation_snapshot: { pricing: details, lot_count: lots.length, conference_count: conferences.length } }; }
