export function money(value) { const number = Number(value || 0); return Math.round((Number.isFinite(number) ? number : 0) * 100) / 100; }
export function number(value) { const parsed = Number(value || 0); return Number.isFinite(parsed) ? parsed : 0; }
export function dateValue(record, fields = []) { for (const field of fields) { const value = record?.[field]; if (value) { const timestamp = new Date(value).getTime(); if (!Number.isNaN(timestamp)) return timestamp; } } return 0; }
export function inPeriod(record, start, end, fields = ['occurred_at', 'completed_at', 'created_date', 'created_at']) { const timestamp = dateValue(record, fields); return timestamp >= start && timestamp < end; }
export function inUnits(record, unitIds) { return !unitIds?.length || unitIds.includes(record?.unit_id); }
export function groupSum(rows, keyFn, valueFn) { const map = new Map(); for (const row of rows || []) { const key = keyFn(row) || 'Não informado'; map.set(key, number(map.get(key)) + number(valueFn(row))); } return [...map.entries()].map(([label, value]) => ({ label, value: money(value) })).sort((a, b) => b.value - a.value); }
export function groupCount(rows, keyFn) { const map = new Map(); for (const row of rows || []) { const key = keyFn(row) || 'Não informado'; map.set(key, number(map.get(key)) + 1); } return [...map.entries()].map(([label, value]) => ({ label, value })).sort((a, b) => b.value - a.value); }
export function dailySeries(rows, valueFn, dateFields = ['occurred_at', 'completed_at', 'created_date', 'created_at']) { const map = new Map(); for (const row of rows || []) { const timestamp = dateValue(row, dateFields); if (!timestamp) continue; const key = new Date(timestamp).toISOString().slice(0, 10); map.set(key, number(map.get(key)) + number(valueFn(row))); } return [...map.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([date, value]) => ({ date, value: money(value) })); }
export function average(values) { const finite = (values || []).map(number).filter((value) => Number.isFinite(value)); return finite.length ? money(finite.reduce((sum, value) => sum + value, 0) / finite.length) : 0; }
export function percent(part, total) { return total > 0 ? Math.round(part / total * 10000) / 100 : 0; }
export function openStatus(status) { return !['completed', 'delivered', 'cancelled', 'paid', 'closed', 'authorized', 'returned'].includes(String(status || '').toLowerCase()); }
export function reportEnvelope(type, summary, series = [], breakdowns = [], rows = [], definitions = [], quality = {}) { return { report_type: type, summary, series, breakdowns, rows, definitions, generated_at: new Date().toISOString(), data_quality: { rows_considered: rows.length, ...quality } }; }
