import React, { useEffect, useMemo, useState } from 'react';
import { Activity, ClipboardCheck, RefreshCw, Scale, ShieldCheck, Truck } from 'lucide-react';
import { base44 } from '@/api/base44Client';

const input = 'w-full rounded-xl border border-white/10 bg-black/15 px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-400/60'; const button = 'rounded-xl bg-cyan-400 px-4 py-2.5 text-sm font-semibold text-slate-950 hover:bg-cyan-300 disabled:opacity-40';
const unwrap = (response) => response?.data || response || {}; const err = (error) => error?.response?.data?.error || error?.data?.error || error?.message || 'Falha na operação hospitalar.';
export default function HospitalLaundry() {
  const [scope, setScope] = useState({ legal_entities: [] }); const [companyId, setCompanyId] = useState(''); const [data, setData] = useState({ pickups: [], weighings: [], processing_lots: [], delivery_conferences: [], billing_measurements: [], contracts: [], parties: [] }); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(null); const [pickup, setPickup] = useState({ contract_id: '', scheduled_at: '', estimated_weight_kg: '0', contamination_class: 'standard', reason: 'Coleta hospitalar programada conforme contrato.' }); const [weight, setWeight] = useState({ pickup_id: '', gross: '', tare: '', category: '', reason: 'Pesagem conferida na recepção hospitalar.' }); const [measurement, setMeasurement] = useState({ contract_id: '', start: '', end: '', reason: 'Medição calculada com base nos lotes entregues e conferidos.' });
  const contracts = useMemo(() => data.contracts.filter((item) => item.status === 'active'), [data.contracts]);
  const load = async (legalEntityId = companyId) => { if (!legalEntityId) return; setBusy(true); try { setData(unwrap(await base44.functions.invoke('manage_hospital_laundry', { action: 'overview', legal_entity_id: legalEntityId }))); setNotice(null); } catch (error) { setNotice({ type: 'error', text: err(error) }); } finally { setBusy(false); } };
  useEffect(() => { (async () => { setBusy(true); try { const enterprise = unwrap(await base44.functions.invoke('manage_enterprise_core', { action: 'overview' })); setScope(enterprise); const id = enterprise.legal_entities?.[0]?.id || ''; setCompanyId(id); if (id) await load(id); } catch (error) { setNotice({ type: 'error', text: err(error) }); } finally { setBusy(false); } })(); }, []);
  const act = async (body, message) => { setBusy(true); try { await base44.functions.invoke('manage_hospital_laundry', body); setNotice({ type: 'success', text: message }); await load(); } catch (error) { setNotice({ type: 'error', text: err(error) }); } finally { setBusy(false); } };
  const contract = contracts.find((item) => item.id === pickup.contract_id); const unassignedWeights = data.weighings.filter((item) => item.direction === 'incoming_soiled' && !item.hospital_processing_lot_id); const openLots = data.processing_lots.filter((item) => !['delivered', 'cancelled'].includes(item.status));
  return <div className="space-y-6"><header><div className="mb-2 flex items-center gap-2 text-sm font-medium text-cyan-300"><Activity className="h-4 w-4" /> Operação industrial</div><h1 className="text-3xl font-bold text-white">Lavanderia hospitalar</h1><p className="mt-2 text-sm text-white/55">Contrato, coleta, pesagem, classificação, processamento, qualidade, expedição, conferência e medição por CNPJ.</p></header>
    {notice && <div className={`rounded-xl border p-3 text-sm ${notice.type === 'error' ? 'border-red-400/25 bg-red-500/10 text-red-200' : 'border-emerald-400/25 bg-emerald-500/10 text-emerald-200'}`}>{notice.text}</div>}
    <div className="flex gap-3 rounded-2xl border border-white/10 bg-white/[0.04] p-4"><select className={input} value={companyId} onChange={(event) => { setCompanyId(event.target.value); load(event.target.value); }}><option value="">Selecione o CNPJ</option>{scope.legal_entities.map((item) => <option key={item.id} value={item.id}>{item.trade_name || item.legal_name}</option>)}</select><button className="rounded-xl border border-white/10 px-4" onClick={() => load()}><RefreshCw className={`h-4 w-4 ${busy ? 'animate-spin' : ''}`} /></button></div>
    <section className="grid gap-3 md:grid-cols-4">{[['Coletas abertas', data.pickups.filter((item) => !['weighed', 'cancelled'].includes(item.status)).length], ['Peso líquido', `${data.weighings.reduce((sum, item) => sum + Number(item.net_weight_kg || 0), 0).toFixed(1)} kg`], ['Lotes em processo', openLots.length], ['Medições', data.billing_measurements.length]].map(([label, value]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[0.04] p-4"><p className="text-xs uppercase text-white/35">{label}</p><p className="mt-2 text-2xl font-bold text-white">{value}</p></div>)}</section>
    <section className="grid gap-6 xl:grid-cols-3"><Panel icon={Truck} title="Programar coleta"><select className={input} value={pickup.contract_id} onChange={(event) => setPickup((current) => ({ ...current, contract_id: event.target.value }))}><option value="">Contrato hospitalar</option>{contracts.map((item) => <option key={item.id} value={item.id}>{item.contract_number} · {item.title}</option>)}</select><input className={input} type="datetime-local" value={pickup.scheduled_at} onChange={(event) => setPickup((current) => ({ ...current, scheduled_at: event.target.value }))} /><input className={input} type="number" min="0" step="0.1" placeholder="Peso estimado (kg)" value={pickup.estimated_weight_kg} onChange={(event) => setPickup((current) => ({ ...current, estimated_weight_kg: event.target.value }))} /><select className={input} value={pickup.contamination_class} onChange={(event) => setPickup((current) => ({ ...current, contamination_class: event.target.value }))}><option value="standard">Padrão</option><option value="infectious">Infectante</option><option value="chemical">Química</option><option value="mixed">Mista</option></select><input className={input} value={pickup.reason} onChange={(event) => setPickup((current) => ({ ...current, reason: event.target.value }))} /><button className={button} disabled={busy || !contract || !pickup.scheduled_at} onClick={() => act({ action: 'schedule_pickup', legal_entity_id: companyId, unit_id: contract?.unit_id, business_contract_id: pickup.contract_id, scheduled_at: new Date(pickup.scheduled_at).toISOString(), estimated_weight_kg: Number(pickup.estimated_weight_kg), contamination_class: pickup.contamination_class, reason: pickup.reason, idempotency_key: crypto.randomUUID() }, 'Coleta hospitalar programada.')}>Programar</button></Panel>
      <Panel icon={Scale} title="Pesagem de entrada"><select className={input} value={weight.pickup_id} onChange={(event) => setWeight((current) => ({ ...current, pickup_id: event.target.value }))}><option value="">Coleta aguardando pesagem</option>{data.pickups.filter((item) => !['weighed', 'cancelled'].includes(item.status)).map((item) => <option key={item.id} value={item.id}>{item.pickup_number}</option>)}</select><input className={input} type="number" min="0" step="0.001" placeholder="Peso bruto kg" value={weight.gross} onChange={(event) => setWeight((current) => ({ ...current, gross: event.target.value }))} /><input className={input} type="number" min="0" step="0.001" placeholder="Tara kg" value={weight.tare} onChange={(event) => setWeight((current) => ({ ...current, tare: event.target.value }))} /><input className={input} placeholder="Categoria do enxoval" value={weight.category} onChange={(event) => setWeight((current) => ({ ...current, category: event.target.value }))} /><input className={input} value={weight.reason} onChange={(event) => setWeight((current) => ({ ...current, reason: event.target.value }))} /><button className={button} disabled={busy || !weight.pickup_id || !weight.gross} onClick={() => { const selected = data.pickups.find((item) => item.id === weight.pickup_id); act({ action: 'record_weighing', hospital_pickup_id: selected.id, business_contract_id: selected.business_contract_id, gross_weight_kg: Number(weight.gross), tare_weight_kg: Number(weight.tare), linen_category: weight.category, contamination_class: selected.contamination_class, reason: weight.reason, idempotency_key: crypto.randomUUID() }, 'Pesagem registrada.'); }}>Registrar peso</button></Panel>
      <Panel icon={ClipboardCheck} title="Fechar medição"><select className={input} value={measurement.contract_id} onChange={(event) => setMeasurement((current) => ({ ...current, contract_id: event.target.value }))}><option value="">Contrato</option>{contracts.map((item) => <option key={item.id} value={item.id}>{item.contract_number}</option>)}</select><input className={input} type="date" value={measurement.start} onChange={(event) => setMeasurement((current) => ({ ...current, start: event.target.value }))} /><input className={input} type="date" value={measurement.end} onChange={(event) => setMeasurement((current) => ({ ...current, end: event.target.value }))} /><input className={input} value={measurement.reason} onChange={(event) => setMeasurement((current) => ({ ...current, reason: event.target.value }))} /><button className={button} disabled={busy || !measurement.contract_id || !measurement.start || !measurement.end} onClick={() => act({ action: 'calculate_measurement', business_contract_id: measurement.contract_id, period_start: `${measurement.start}T00:00:00.000Z`, period_end: `${measurement.end}T23:59:59.999Z`, reason: measurement.reason, idempotency_key: crypto.randomUUID() }, 'Medição calculada para conferência.')}>Calcular medição</button></Panel></section>
    <section className="grid gap-6 xl:grid-cols-2"><List title="Pesagens sem lote" rows={unassignedWeights} empty="Nenhuma pesagem aguardando classificação." render={(item) => <Row key={item.id} title={item.weighing_number} subtitle={`${item.net_weight_kg} kg · ${item.linen_category || 'sem categoria'}`} status={item.quality_status}><button className={button} onClick={() => act({ action: 'create_processing_lot', weighing_record_id: item.id, linen_category: item.linen_category, reason: 'Lote classificado a partir da pesagem de entrada.', idempotency_key: crypto.randomUUID() }, 'Lote hospitalar criado.')}>Criar lote</button></Row>} />
      <List title="Lotes de processamento" rows={data.processing_lots} empty="Nenhum lote." render={(item) => <Row key={item.id} title={item.lot_number} subtitle={`${item.incoming_weight_kg || 0} kg · ${item.contamination_class}`} status={item.status}><LotAction item={item} act={act} /></Row>} /></section>
    <section className="grid gap-6 xl:grid-cols-2"><List title="Medições hospitalares" rows={data.billing_measurements} empty="Nenhuma medição." render={(item) => <Row key={item.id} title={item.measurement_number} subtitle={`R$ ${Number(item.total_amount || 0).toFixed(2)} · ${item.billable_weight_kg || 0} kg`} status={item.status}>{item.status === 'calculated' && <button className={button} onClick={() => act({ action: 'approve_measurement', hospital_billing_measurement_id: item.id, reason: 'Medição conferida e aprovada para contas a receber.' }, 'Medição aprovada e conta a receber criada.')}>Aprovar</button>}</Row>} />
      <List title="Conferências de entrega" rows={data.delivery_conferences} empty="Nenhuma conferência." render={(item) => <Row key={item.id} title={item.conference_number} subtitle={`${item.accepted_weight_kg || 0} kg · ${item.accepted_piece_count || 0} peças`} status={item.status} />} /></section>
  </div>;
}
function Panel({ icon: Icon, title, children }) { return <div className="space-y-3 rounded-2xl border border-white/10 bg-white/[0.04] p-5"><h2 className="flex items-center gap-2 font-semibold text-white"><Icon className="h-4 w-4 text-cyan-300" />{title}</h2>{children}</div>; }
function List({ title, rows, empty, render }) { return <section className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><h2 className="font-semibold text-white">{title}</h2><div className="mt-4 space-y-2">{rows.slice(0, 100).map(render)}{!rows.length && <p className="text-sm text-white/35">{empty}</p>}</div></section>; }
function Row({ title, subtitle, status, children = null }) { return <div className="flex flex-col justify-between gap-3 rounded-xl border border-white/8 bg-black/10 p-3 sm:flex-row sm:items-center"><div><p className="text-sm font-medium text-white">{title}</p><p className="text-xs text-white/40">{subtitle}</p></div><div className="flex flex-wrap items-center gap-2"><span className="text-xs text-cyan-200">{status}</span>{children}</div></div>; }
function LotAction({ item, act }) { const next = { classified: ['queue', 'Enfileirar'], queued: ['start_wash', 'Iniciar lavagem'], washing: ['start_dry', 'Iniciar secagem'], drying: ['start_finish', 'Iniciar acabamento'], finishing: ['submit_quality', 'Enviar à qualidade'], quality: ['approve_quality', 'Aprovar qualidade'], approved: ['release_expedition', 'Liberar expedição'] }[item.status]; if (next) return <button className={button} onClick={() => act({ action: 'advance_processing_lot', hospital_processing_lot_id: item.id, transition: next[0], reason: `${next[1]} conforme procedimento operacional.` }, `${next[1]} concluído.`)}>{next[1]}</button>; if (item.status === 'expedition') return <button className={button} onClick={() => act({ action: 'conference_delivery', hospital_processing_lot_id: item.id, delivered_weight_kg: item.clean_weight_kg || item.incoming_weight_kg, accepted_weight_kg: item.clean_weight_kg || item.incoming_weight_kg, delivered_piece_count: item.piece_count || 0, accepted_piece_count: item.piece_count || 0, conferred_by_name: 'Responsável do cliente', reason: 'Entrega conferida sem divergência.', idempotency_key: crypto.randomUUID() }, 'Entrega conferida.')}>Conferir entrega</button>; return <ShieldCheck className="h-4 w-4 text-white/30" />; }
