import React, { useEffect, useMemo, useState } from 'react';
import { ArrowRightLeft, Boxes, ClipboardCheck, Loader2, PackageCheck, RefreshCw, ShoppingCart } from 'lucide-react';
import { base44 } from '@/api/base44Client';

function unwrap(response) { return response?.data || response || {}; }
function errorText(error) { return error?.response?.data?.error || error?.data?.error || error?.message || 'Falha na operação de compras.'; }
const inputClass = 'w-full rounded-xl border border-white/10 bg-black/15 px-3 py-2.5 text-sm text-white outline-none focus:border-orange-400/60';
const buttonClass = 'rounded-xl bg-orange-500 px-4 py-2.5 text-sm font-semibold text-slate-950 hover:bg-orange-400 disabled:opacity-40';
const statusColor = (status) => status === 'approved' || status === 'received' || status === 'accepted' || status === 'closed' ? 'text-emerald-300' : status === 'rejected' || status === 'cancelled' || status === 'quality_hold' ? 'text-red-300' : 'text-amber-200';

export default function ProcurementOperations() {
  const [scope, setScope] = useState({ legal_entities: [], units: [] }); const [companyId, setCompanyId] = useState(''); const [warehouseId, setWarehouseId] = useState(''); const [data, setData] = useState({ requisitions: [], requisition_items: [], purchase_orders: [], purchase_order_items: [], receipts: [], suppliers: [], warehouses: [], stock_items: [], purchase_documents: [] }); const [transfers, setTransfers] = useState({ transfers: [], items: [] }); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(null);
  const [requestForm, setRequestForm] = useState({ stock_item_id: '', description: '', quantity: '1', estimated_unit_price: '0', priority: 'normal', reason: 'Reposição operacional planejada.' });
  const [orderForm, setOrderForm] = useState({ requisition_id: '', supplier_id: '', reason: 'Pedido de compra vinculado à requisição aprovada.' });
  const [transferForm, setTransferForm] = useState({ source_warehouse_id: '', destination_warehouse_id: '', stock_item_id: '', quantity: '1', reason: 'Transferência operacional entre depósitos.' });
  const warehouses = useMemo(() => data.warehouses.filter((item) => item.legal_entity_id === companyId), [data.warehouses, companyId]); const selectedWarehouse = warehouses.find((item) => item.id === warehouseId); const stockItems = data.stock_items.filter((item) => item.warehouse_id === warehouseId); const openOrders = data.purchase_orders.filter((item) => ['sent', 'partially_received'].includes(item.status));

  const load = async (legalEntityId = companyId) => { if (!legalEntityId) return; setBusy(true); try { const [overview, transferOverview] = await Promise.all([base44.functions.invoke('manage_procurement_core', { action: 'overview', legal_entity_id: legalEntityId }), base44.functions.invoke('manage_stock_transfers', { action: 'overview', legal_entity_id: legalEntityId })]); const next = unwrap(overview); setData(next); setTransfers(unwrap(transferOverview)); const nextWarehouse = next.warehouses?.find((item) => item.legal_entity_id === legalEntityId)?.id || ''; setWarehouseId((current) => next.warehouses?.some((item) => item.id === current && item.legal_entity_id === legalEntityId) ? current : nextWarehouse); setNotice(null); } catch (error) { setNotice({ type: 'error', text: errorText(error) }); } finally { setBusy(false); } };
  useEffect(() => { (async () => { setBusy(true); try { const enterprise = unwrap(await base44.functions.invoke('manage_enterprise_core', { action: 'overview' })); setScope(enterprise); const id = enterprise.legal_entities?.[0]?.id || ''; setCompanyId(id); if (id) await load(id); } catch (error) { setNotice({ type: 'error', text: errorText(error) }); } finally { setBusy(false); } })(); }, []);
  const act = async (payload, success) => { setBusy(true); try { await base44.functions.invoke(payload.function || 'manage_procurement_core', payload.body); setNotice({ type: 'success', text: success }); await load(); } catch (error) { setNotice({ type: 'error', text: errorText(error) }); } finally { setBusy(false); } };
  const createRequisition = () => { if (!warehouseId || (!requestForm.stock_item_id && !requestForm.description.trim())) return setNotice({ type: 'error', text: 'Selecione um item ou informe a descrição.' }); const item = data.stock_items.find((row) => row.id === requestForm.stock_item_id); act({ body: { action: 'create_requisition', legal_entity_id: companyId, unit_id: selectedWarehouse?.unit_id, warehouse_id: warehouseId, priority: requestForm.priority, reason: requestForm.reason, idempotency_key: crypto.randomUUID(), items: [{ stock_item_id: item?.id, description: item?.name || requestForm.description, requested_quantity: Number(requestForm.quantity), purchase_unit: item?.purchase_unit || item?.base_unit || 'unit', estimated_unit_price: Number(requestForm.estimated_unit_price) }] } }, 'Requisição enviada para aprovação.'); };
  const createOrder = () => act({ body: { action: 'create_purchase_order', purchase_requisition_id: orderForm.requisition_id, supplier_id: orderForm.supplier_id, reason: orderForm.reason, idempotency_key: crypto.randomUUID() } }, 'Pedido de compra criado para aprovação.');
  const createTransfer = () => act({ function: 'manage_stock_transfers', body: { action: 'create', legal_entity_id: companyId, source_warehouse_id: transferForm.source_warehouse_id, destination_warehouse_id: transferForm.destination_warehouse_id, reason: transferForm.reason, idempotency_key: crypto.randomUUID(), items: [{ stock_item_id: transferForm.stock_item_id, quantity: Number(transferForm.quantity) }] } }, 'Transferência criada para aprovação.');

  return <div className="space-y-6"><header><div className="mb-2 flex items-center gap-2 text-sm font-medium text-orange-300"><ShoppingCart className="h-4 w-4" /> Suprimentos corporativos</div><h1 className="text-3xl font-bold text-white">Compras e estoque por depósito</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-white/55">Requisição, alçada, pedido, recebimento físico, lotes, divergências e transferências segregados por CNPJ.</p></header>
    {notice && <div className={`rounded-xl border px-4 py-3 text-sm ${notice.type === 'error' ? 'border-red-400/25 bg-red-400/10 text-red-200' : 'border-emerald-400/25 bg-emerald-400/10 text-emerald-200'}`}>{notice.text}</div>}
    <section className="grid gap-3 rounded-2xl border border-white/10 bg-white/[0.04] p-5 md:grid-cols-[1fr_1fr_auto]"><select className={inputClass} value={companyId} onChange={(event) => { setCompanyId(event.target.value); load(event.target.value); }}><option value="">Selecione o CNPJ</option>{scope.legal_entities.map((item) => <option key={item.id} value={item.id}>{item.trade_name || item.legal_name}</option>)}</select><select className={inputClass} value={warehouseId} onChange={(event) => setWarehouseId(event.target.value)}><option value="">Selecione o depósito</option>{warehouses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button type="button" className="rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-white/60" onClick={() => load()}><RefreshCw className={`inline h-4 w-4 ${busy ? 'animate-spin' : ''}`} /></button></section>
    <section className="grid gap-3 md:grid-cols-4">{[['Requisições pendentes', data.requisitions.filter((item) => item.status === 'submitted').length], ['Pedidos abertos', data.purchase_orders.filter((item) => !['received', 'closed', 'cancelled'].includes(item.status)).length], ['Recebimentos', data.receipts.length], ['Itens no depósito', stockItems.length]].map(([label, value]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[0.04] p-4"><p className="text-xs uppercase text-white/35">{label}</p><p className="mt-2 text-2xl font-bold text-white">{value}</p></div>)}</section>
    <section className="grid gap-6 xl:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><h2 className="flex items-center gap-2 font-semibold text-white"><ClipboardCheck className="h-4 w-4 text-orange-300" />Nova requisição</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><select className={inputClass} value={requestForm.stock_item_id} onChange={(event) => setRequestForm((current) => ({ ...current, stock_item_id: event.target.value }))}><option value="">Item do catálogo</option>{stockItems.map((item) => <option key={item.id} value={item.id}>{item.name} · saldo {item.current_quantity || 0}</option>)}</select><input className={inputClass} placeholder="Descrição avulsa" value={requestForm.description} onChange={(event) => setRequestForm((current) => ({ ...current, description: event.target.value }))} /><input className={inputClass} type="number" min="0.000001" step="0.001" value={requestForm.quantity} onChange={(event) => setRequestForm((current) => ({ ...current, quantity: event.target.value }))} placeholder="Quantidade" /><input className={inputClass} type="number" min="0" step="0.01" value={requestForm.estimated_unit_price} onChange={(event) => setRequestForm((current) => ({ ...current, estimated_unit_price: event.target.value }))} placeholder="Preço estimado" /><select className={inputClass} value={requestForm.priority} onChange={(event) => setRequestForm((current) => ({ ...current, priority: event.target.value }))}><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option><option value="low">Baixa</option></select><input className={inputClass} value={requestForm.reason} onChange={(event) => setRequestForm((current) => ({ ...current, reason: event.target.value }))} /></div><button className={`${buttonClass} mt-4 w-full`} disabled={busy || !warehouseId} onClick={createRequisition}>{busy ? <Loader2 className="mr-2 inline h-4 w-4 animate-spin" /> : null}Enviar para aprovação</button></div>
      <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><h2 className="flex items-center gap-2 font-semibold text-white"><PackageCheck className="h-4 w-4 text-orange-300" />Pedido a partir da requisição</h2><div className="mt-4 space-y-3"><select className={inputClass} value={orderForm.requisition_id} onChange={(event) => setOrderForm((current) => ({ ...current, requisition_id: event.target.value }))}><option value="">Requisição aprovada</option>{data.requisitions.filter((item) => item.status === 'approved').map((item) => <option key={item.id} value={item.id}>{item.request_number}</option>)}</select><select className={inputClass} value={orderForm.supplier_id} onChange={(event) => setOrderForm((current) => ({ ...current, supplier_id: event.target.value }))}><option value="">Fornecedor</option>{data.suppliers.filter((item) => item.status !== 'blocked').map((item) => <option key={item.id} value={item.id}>{item.name || item.legal_name}</option>)}</select><input className={inputClass} value={orderForm.reason} onChange={(event) => setOrderForm((current) => ({ ...current, reason: event.target.value }))} /></div><button className={`${buttonClass} mt-4 w-full`} disabled={busy || !orderForm.requisition_id || !orderForm.supplier_id} onClick={createOrder}>Criar pedido</button></div></section>
    <section className="grid gap-6 xl:grid-cols-2"><List title="Requisições" icon={ClipboardCheck} rows={data.requisitions} empty="Nenhuma requisição." render={(item) => <Row key={item.id} title={item.request_number} subtitle={`${item.priority} · R$ ${Number(item.estimated_total || 0).toFixed(2)}`} status={item.status}>{item.status === 'submitted' && <button className={buttonClass} onClick={() => act({ body: { action: 'approve_requisition', purchase_requisition_id: item.id, reason: 'Requisição aprovada conforme necessidade operacional.' } }, 'Requisição aprovada.')}>Aprovar</button>}</Row>} />
      <List title="Pedidos de compra" icon={ShoppingCart} rows={data.purchase_orders} empty="Nenhum pedido." render={(item) => <Row key={item.id} title={item.order_number} subtitle={`R$ ${Number(item.total || 0).toFixed(2)}`} status={item.status}>{item.status === 'submitted' && <button className={buttonClass} onClick={() => act({ body: { action: 'approve_purchase_order', purchase_order_id: item.id, reason: 'Pedido aprovado dentro da alçada corporativa.' } }, 'Pedido aprovado.')}>Aprovar</button>}{item.status === 'approved' && <button className={buttonClass} onClick={() => act({ body: { action: 'mark_purchase_order_sent', purchase_order_id: item.id, reason: 'Pedido enviado ao fornecedor por canal corporativo.' } }, 'Pedido marcado como enviado.')}>Marcar enviado</button>}</Row>} /></section>
    <section className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><h2 className="flex items-center gap-2 font-semibold text-white"><PackageCheck className="h-4 w-4 text-emerald-300" />Recebimento físico</h2><div className="mt-4 grid gap-3">{openOrders.map((order) => { const lines = data.purchase_order_items.filter((item) => item.purchase_order_id === order.id).filter((item) => Number(item.received_quantity || 0) < Number(item.ordered_quantity || 0)); return <div key={order.id} className="rounded-xl border border-white/8 bg-black/10 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium text-white">{order.order_number}</p><p className="text-xs text-white/40">{lines.length} linha(s) pendente(s)</p></div><button className={buttonClass} disabled={!lines.length} onClick={() => act({ body: { action: 'receive_purchase_order', purchase_order_id: order.id, reason: 'Recebimento conferido fisicamente no depósito.', idempotency_key: crypto.randomUUID(), items: lines.map((line) => ({ purchase_order_item_id: line.id, stock_item_id: line.stock_item_id, received_quantity: Number(line.ordered_quantity || 0) - Number(line.received_quantity || 0), accepted_quantity: Number(line.ordered_quantity || 0) - Number(line.received_quantity || 0), rejected_quantity: 0 })) } }, 'Recebimento registrado e estoque atualizado.')}>Receber saldo integral</button></div></div>; })}{!openOrders.length && <p className="text-sm text-white/35">Nenhum pedido enviado aguardando recebimento.</p>}</div></section>
    <section className="grid gap-6 xl:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><h2 className="flex items-center gap-2 font-semibold text-white"><ArrowRightLeft className="h-4 w-4 text-sky-300" />Nova transferência</h2><div className="mt-4 space-y-3"><select className={inputClass} value={transferForm.source_warehouse_id} onChange={(event) => { const source = event.target.value; setTransferForm((current) => ({ ...current, source_warehouse_id: source, stock_item_id: '' })); }}><option value="">Depósito de origem</option>{warehouses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className={inputClass} value={transferForm.destination_warehouse_id} onChange={(event) => setTransferForm((current) => ({ ...current, destination_warehouse_id: event.target.value }))}><option value="">Depósito de destino</option>{warehouses.filter((item) => item.id !== transferForm.source_warehouse_id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className={inputClass} value={transferForm.stock_item_id} onChange={(event) => setTransferForm((current) => ({ ...current, stock_item_id: event.target.value }))}><option value="">Item</option>{data.stock_items.filter((item) => item.warehouse_id === transferForm.source_warehouse_id).map((item) => <option key={item.id} value={item.id}>{item.name} · {item.current_quantity || 0}</option>)}</select><input className={inputClass} type="number" min="0.000001" step="0.001" value={transferForm.quantity} onChange={(event) => setTransferForm((current) => ({ ...current, quantity: event.target.value }))} /><input className={inputClass} value={transferForm.reason} onChange={(event) => setTransferForm((current) => ({ ...current, reason: event.target.value }))} /></div><button className={`${buttonClass} mt-4 w-full`} disabled={busy || !transferForm.source_warehouse_id || !transferForm.destination_warehouse_id || !transferForm.stock_item_id} onClick={createTransfer}>Criar transferência</button></div>
      <List title="Transferências" icon={ArrowRightLeft} rows={transfers.transfers || []} empty="Nenhuma transferência." render={(item) => <Row key={item.id} title={item.transfer_number} subtitle="Expedição e recebimento separados" status={item.status}>{item.status === 'draft' && <button className={buttonClass} onClick={() => act({ function: 'manage_stock_transfers', body: { action: 'approve', stock_transfer_id: item.id, reason: 'Transferência aprovada para execução.' } }, 'Transferência aprovada.')}>Aprovar</button>}{item.status === 'approved' && <button className={buttonClass} onClick={() => act({ function: 'manage_stock_transfers', body: { action: 'dispatch', stock_transfer_id: item.id, reason: 'Itens conferidos e expedidos no depósito de origem.' } }, 'Transferência expedida.')}>Expedir</button>}{['dispatched', 'partially_received'].includes(item.status) && <button className={buttonClass} onClick={() => act({ function: 'manage_stock_transfers', body: { action: 'receive', stock_transfer_id: item.id, reason: 'Itens conferidos no depósito de destino.', idempotency_key: crypto.randomUUID() } }, 'Transferência recebida.')}>Receber</button>}</Row>} /></section>
    <List title="Posição do depósito" icon={Boxes} rows={stockItems} empty="Nenhum item no depósito selecionado." render={(item) => <Row key={item.id} title={item.name} subtitle={`${item.sku} · ${item.current_quantity || 0} ${item.base_unit}`} status={Number(item.current_quantity || 0) <= Number(item.minimum_quantity || 0) ? 'baixo' : 'normal'} />} />
  </div>;
}

function List({ title, icon: Icon, rows, empty, render }) { return <section className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><h2 className="flex items-center gap-2 font-semibold text-white"><Icon className="h-4 w-4 text-orange-300" />{title}</h2><div className="mt-4 space-y-2">{rows.slice(0, 100).map(render)}{!rows.length && <p className="text-sm text-white/35">{empty}</p>}</div></section>; }
function Row({ title, subtitle, status, children = null }) { return <div className="flex flex-col justify-between gap-3 rounded-xl border border-white/8 bg-black/10 p-3 sm:flex-row sm:items-center"><div><p className="text-sm font-medium text-white">{title}</p><p className="text-xs text-white/40">{subtitle}</p></div><div className="flex items-center gap-2"><span className={`text-xs ${statusColor(status)}`}>{status}</span>{children}</div></div>; }
