import { useMemo, useState } from 'react';
import { Beaker, Loader2, Plus, Power, Save, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';

const BASES = { per_piece: 'Por peça', per_kg: 'Por kg', per_cycle: 'Por ciclo', per_square_meter: 'Por m²' };
const STAGES = { washing: 'Lavagem', drying: 'Secagem', dry_cleaning: 'Lavagem a seco', ironing: 'Passadoria', finishing: 'Finalização', quality_control: 'Qualidade', packaging: 'Embalagem' };
const money = (value) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value || 0));

export default function ConsumptionRecipesPanel({ recipes = [], stockItems = [], services = [], machines = [], selectedUnitId, onRefresh }) {
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ name: '', service_id: '', product_id: '', stage: 'washing', machine_type: 'wash', basis: 'per_piece', waste_tolerance_percent: 5, items: [{ stock_item_id: '', quantity: '', unit: '' }] });
  const scoped = useMemo(() => recipes.filter((recipe) => selectedUnitId === 'all' || recipe.unit_id === selectedUnitId), [recipes, selectedUnitId]);
  const activeStock = stockItems.filter((item) => item.active !== false && (selectedUnitId === 'all' || item.unit_id === selectedUnitId));
  const patchItem = (index, field, value) => setForm((state) => ({ ...state, items: state.items.map((line, i) => i === index ? { ...line, [field]: value } : line) }));
  const addItem = () => setForm((state) => ({ ...state, items: [...state.items, { stock_item_id: '', quantity: '', unit: '' }] }));
  const removeItem = (index) => setForm((state) => ({ ...state, items: state.items.filter((_, i) => i !== index) }));

  const submit = async () => {
    if (!selectedUnitId || selectedUnitId === 'all') return toast.error('Selecione uma unidade específica.');
    if (!form.name.trim() || form.items.some((line) => !line.stock_item_id || Number(line.quantity) <= 0)) return toast.error('Informe nome e todos os insumos da ficha.');
    setBusy(true);
    try {
      await base44.functions.invoke('manage_consumption_recipe', { action: 'create_version', unit_id: selectedUnitId, ...form, active: true, items: form.items.map((line) => ({ ...line, quantity: Number(line.quantity), unit: line.unit || activeStock.find((item) => item.id === line.stock_item_id)?.base_unit })) });
      toast.success('Nova versão da ficha técnica ativada.'); setOpen(false); onRefresh?.();
    } catch (error) { console.error(error); toast.error('Não foi possível salvar a ficha técnica.'); }
    finally { setBusy(false); }
  };

  const deactivate = async (recipe) => {
    const reason = window.prompt('Motivo da desativação:'); if (!reason?.trim()) return;
    setBusy(true); try { await base44.functions.invoke('manage_consumption_recipe', { action: 'deactivate', recipe_id: recipe.id, reason }); toast.success('Ficha desativada.'); onRefresh?.(); } catch (error) { console.error(error); toast.error('Não foi possível desativar.'); } finally { setBusy(false); }
  };

  return <section className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-lg font-semibold text-white">Fichas técnicas de consumo</h3><p className="text-sm text-white/45">Versões auditadas para prever e baixar insumos automaticamente.</p></div><Button onClick={() => setOpen(true)} className="bg-gradient-to-r from-cyan-500 to-violet-500"><Plus className="mr-2 h-4 w-4" />Nova ficha</Button></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{scoped.map((recipe) => <article key={recipe.id} className="rounded-3xl border border-white/10 bg-white/[0.03] p-5"><div className="flex items-start justify-between gap-3"><div className="rounded-2xl bg-cyan-500/10 p-2 text-cyan-300"><Beaker className="h-5 w-5" /></div><Badge variant="outline" className={recipe.active ? 'border-emerald-500/30 text-emerald-300' : 'border-white/10 text-white/40'}>{recipe.active ? 'Ativa' : 'Inativa'} · v{recipe.version}</Badge></div><h4 className="mt-4 font-semibold text-white">{recipe.name}</h4><p className="mt-1 text-xs text-white/40">{STAGES[recipe.stage] || recipe.stage} · {BASES[recipe.basis] || recipe.basis} · tolerância {recipe.waste_tolerance_percent ?? 5}%</p><div className="mt-4 space-y-2">{(recipe.items || []).map((line, index) => <div key={`${line.stock_item_id}-${index}`} className="flex justify-between text-sm"><span className="text-white/55">{stockItems.find((item) => item.id === line.stock_item_id)?.name || line.stock_item_id}</span><span className="font-medium text-white">{line.quantity} {line.unit}</span></div>)}</div><div className="mt-4 flex items-center justify-between border-t border-white/10 pt-4"><div><p className="text-xs text-white/35">Custo-base</p><p className="font-semibold text-cyan-300">{money(recipe.estimated_material_cost)}</p></div>{recipe.active && <Button size="sm" variant="ghost" disabled={busy} onClick={() => deactivate(recipe)} className="text-white/45 hover:text-red-300"><Power className="mr-2 h-4 w-4" />Desativar</Button>}</div></article>)}{scoped.length === 0 && <div className="col-span-full rounded-3xl border border-dashed border-white/10 p-10 text-center text-sm text-white/35">Nenhuma ficha técnica cadastrada.</div>}</div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-3xl border-white/10 bg-[#160d29] text-white"><DialogHeader><DialogTitle>Nova versão de ficha técnica</DialogTitle><DialogDescription className="text-white/45">A versão anterior permanece no histórico. A nova passa a valer para os próximos lotes.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><div><Label>Nome</Label><Input value={form.name} onChange={(e) => setForm((state) => ({ ...state, name: e.target.value }))} className="mt-1 border-white/10 bg-white/5" /></div><div><Label>Serviço (opcional)</Label><select value={form.service_id} onChange={(e) => setForm((state) => ({ ...state, service_id: e.target.value }))} className="mt-1 h-10 w-full rounded-md border border-white/10 bg-[#201334] px-3 text-sm"><option value="">Geral da etapa</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select></div><div><Label>Etapa</Label><select value={form.stage} onChange={(e) => setForm((state) => ({ ...state, stage: e.target.value, machine_type: ({ washing: 'wash', drying: 'dry', dry_cleaning: 'dry_clean', ironing: 'iron', finishing: 'finishing', quality_control: 'quality', packaging: 'packaging' })[e.target.value] }))} className="mt-1 h-10 w-full rounded-md border border-white/10 bg-[#201334] px-3 text-sm">{Object.entries(STAGES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div><Label>Base de cálculo</Label><select value={form.basis} onChange={(e) => setForm((state) => ({ ...state, basis: e.target.value }))} className="mt-1 h-10 w-full rounded-md border border-white/10 bg-[#201334] px-3 text-sm">{Object.entries(BASES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div><Label>Tolerância de desvio (%)</Label><Input type="number" min="0" value={form.waste_tolerance_percent} onChange={(e) => setForm((state) => ({ ...state, waste_tolerance_percent: Number(e.target.value) }))} className="mt-1 border-white/10 bg-white/5" /></div><div><Label>Tipo de máquina</Label><select value={form.machine_type} onChange={(e) => setForm((state) => ({ ...state, machine_type: e.target.value }))} className="mt-1 h-10 w-full rounded-md border border-white/10 bg-[#201334] px-3 text-sm">{[...new Set(machines.map((machine) => machine.machine_type).filter(Boolean))].map((type) => <option key={type} value={type}>{type}</option>)}{machines.length === 0 && <option value={form.machine_type}>{form.machine_type}</option>}</select></div></div>
    <div className="max-h-72 space-y-3 overflow-auto rounded-2xl border border-white/10 p-4"><div className="flex items-center justify-between"><h4 className="font-medium text-white">Insumos por unidade da base</h4><Button size="sm" variant="outline" onClick={addItem} className="border-white/10"><Plus className="mr-2 h-3.5 w-3.5" />Adicionar</Button></div>{form.items.map((line, index) => <div key={index} className="grid gap-2 sm:grid-cols-[1fr_130px_44px]"><select value={line.stock_item_id} onChange={(e) => { const item = activeStock.find((row) => row.id === e.target.value); patchItem(index, 'stock_item_id', e.target.value); patchItem(index, 'unit', item?.base_unit || ''); }} className="h-10 rounded-md border border-white/10 bg-[#201334] px-3 text-sm"><option value="">Selecione o insumo</option>{activeStock.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.base_unit}</option>)}</select><Input type="number" min="0" step="any" value={line.quantity} onChange={(e) => patchItem(index, 'quantity', e.target.value)} placeholder="Quantidade" className="border-white/10 bg-white/5" /><Button size="icon" variant="ghost" onClick={() => removeItem(index)} disabled={form.items.length === 1} className="text-red-300"><Trash2 className="h-4 w-4" /></Button></div>)}</div>
    <div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setOpen(false)} className="border-white/10">Cancelar</Button><Button onClick={submit} disabled={busy}>{busy ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}Salvar versão</Button></div></DialogContent></Dialog>
  </section>;
}
