import { useMemo, useState } from 'react';
import { AlertTriangle, ArrowLeftRight, Beaker, Boxes, ClipboardCheck, History, PackageMinus, PackagePlus, Plus, ReceiptText, Search, Truck, WalletCards } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import StockOperationDialog from './StockOperationDialog';
import InventoryCountPanel from './InventoryCountPanel';
import ConsumptionRecipesPanel from './ConsumptionRecipesPanel';

const money = (value) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value || 0));
const date = (value) => value ? new Date(value).toLocaleDateString('pt-BR') : '—';
const MOVEMENT_LABEL = { purchase_entry: 'Compra', consumption: 'Consumo', consumption_reversal: 'Estorno consumo', adjustment_in: 'Ajuste +', adjustment_out: 'Ajuste −', transfer_in: 'Transferência +', transfer_out: 'Transferência −', loss: 'Perda', return_to_supplier: 'Devolução', inventory_difference: 'Inventário', reservation: 'Reserva', reservation_release: 'Liberação' };

function Stat({ icon: Icon, label, value, hint, tone = 'violet' }) {
  const tones = { violet: 'from-violet-500/20 to-fuchsia-500/5 text-violet-300', amber: 'from-amber-500/20 to-orange-500/5 text-amber-300', emerald: 'from-emerald-500/20 to-teal-500/5 text-emerald-300', sky: 'from-sky-500/20 to-cyan-500/5 text-sky-300' };
  return <div className={`rounded-3xl border border-white/10 bg-gradient-to-br p-5 ${tones[tone]}`}><div className="flex items-center justify-between"><p className="text-sm text-white/50">{label}</p><Icon className="h-5 w-5" /></div><p className="mt-3 text-2xl font-bold text-white">{value}</p><p className="mt-1 text-xs text-white/35">{hint}</p></div>;
}

export default function InventoryPanel({ stockItems = [], stockLots = [], stockMovements = [], inventoryCounts = [], recipes = [], purchaseDocuments = [], suppliers = [], services = [], machines = [], batches = [], units = [], selectedUnitId, onNewPurchase, onRefresh }) {
  const [search, setSearch] = useState('');
  const [operationOpen, setOperationOpen] = useState(false);
  const [operationAction, setOperationAction] = useState('adjust_in');
  const [operationItemId, setOperationItemId] = useState('');
  const scopedStock = useMemo(() => stockItems.filter((item) => (selectedUnitId === 'all' || item.unit_id === selectedUnitId) && `${item.name} ${item.sku} ${item.category} ${item.barcode}`.toLowerCase().includes(search.toLowerCase())), [stockItems, selectedUnitId, search]);
  const scopedLots = stockLots.filter((item) => selectedUnitId === 'all' || item.unit_id === selectedUnitId);
  const scopedMovements = stockMovements.filter((item) => selectedUnitId === 'all' || item.unit_id === selectedUnitId);
  const scopedDocuments = purchaseDocuments.filter((item) => selectedUnitId === 'all' || item.unit_id === selectedUnitId);
  const lowStock = scopedStock.filter((item) => Number(item.current_quantity || 0) <= Number(item.minimum_quantity || 0));
  const inventoryValue = scopedStock.reduce((sum, item) => sum + Number(item.current_quantity || 0) * Number(item.average_cost || 0), 0);
  const pendingDocs = scopedDocuments.filter((item) => ['received', 'extracting', 'human_review'].includes(item.status));
  const expiringLots = scopedLots.filter((lot) => lot.status === 'available' && lot.expiry_date && Date.parse(lot.expiry_date) < Date.now() + 30 * 86400000);
  const stockMap = Object.fromEntries(stockItems.map((item) => [item.id, item]));

  const openOperation = (action, itemId = '') => { setOperationAction(action); setOperationItemId(itemId); setOperationOpen(true); };

  return <section className="space-y-6">
    <div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div><h2 className="text-xl font-semibold text-white">Estoque e consumo</h2><p className="text-sm text-white/45">Compras, lotes, validade, transferências, inventário, fichas técnicas e custos reais.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => openOperation('create_item')} className="border-white/10 bg-white/5"><Plus className="mr-2 h-4 w-4" />Novo insumo</Button><Button variant="outline" onClick={() => openOperation('adjust_in')} className="border-white/10 bg-white/5"><PackagePlus className="mr-2 h-4 w-4" />Movimentar</Button><Button onClick={onNewPurchase} className="bg-gradient-to-r from-orange-500 to-fuchsia-500"><ReceiptText className="mr-2 h-4 w-4" />Ler nota de compra</Button></div></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Stat icon={Boxes} label="Itens ativos" value={scopedStock.length} hint="Catálogo por unidade" /><Stat icon={AlertTriangle} label="Abaixo do mínimo" value={lowStock.length} hint="Reposição recomendada" tone="amber" /><Stat icon={WalletCards} label="Valor em estoque" value={money(inventoryValue)} hint="Saldo × custo médio" tone="emerald" /><Stat icon={ReceiptText} label="Documentos pendentes" value={pendingDocs.length} hint="Extração ou revisão" tone="sky" /><Stat icon={History} label="Lotes a vencer" value={expiringLots.length} hint="Próximos 30 dias" tone="amber" /></div>
    <Tabs defaultValue="position" className="space-y-5"><TabsList className="h-auto w-full justify-start gap-1 overflow-x-auto rounded-2xl bg-white/5 p-1.5"><TabsTrigger value="position" className="gap-2"><Boxes className="h-4 w-4" />Posição</TabsTrigger><TabsTrigger value="lots" className="gap-2"><PackagePlus className="h-4 w-4" />Lotes</TabsTrigger><TabsTrigger value="movements" className="gap-2"><History className="h-4 w-4" />Movimentos</TabsTrigger><TabsTrigger value="inventory" className="gap-2"><ClipboardCheck className="h-4 w-4" />Inventário</TabsTrigger><TabsTrigger value="recipes" className="gap-2"><Beaker className="h-4 w-4" />Fichas técnicas</TabsTrigger></TabsList>
      <TabsContent value="position" className="space-y-5"><div className="relative max-w-md"><Search className="absolute left-3 top-2.5 h-4 w-4 text-white/35" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar insumo, SKU, categoria ou código" className="border-white/10 bg-white/5 pl-9" /></div><div className="overflow-hidden rounded-3xl border border-white/10 bg-white/[0.03]"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-black/15 text-xs uppercase tracking-wide text-white/35"><tr><th className="px-5 py-3">Insumo</th><th className="px-4 py-3 text-right">Saldo</th><th className="px-4 py-3 text-right">Disponível</th><th className="px-4 py-3 text-right">Mínimo</th><th className="px-4 py-3 text-right">Custo médio</th><th className="px-4 py-3">Local</th><th className="px-5 py-3">Ações</th></tr></thead><tbody className="divide-y divide-white/5">{scopedStock.map((item) => { const isLow = Number(item.current_quantity || 0) <= Number(item.minimum_quantity || 0); const available = item.available_quantity ?? Number(item.current_quantity || 0) - Number(item.reserved_quantity || 0); return <tr key={item.id} className="hover:bg-white/[0.03]"><td className="px-5 py-4"><p className="font-medium text-white">{item.name}</p><p className="text-xs text-white/35">{item.sku} · {item.category || 'Sem categoria'}</p></td><td className="px-4 py-4 text-right text-white/75">{Number(item.current_quantity || 0).toLocaleString('pt-BR')} {item.base_unit}</td><td className="px-4 py-4 text-right text-white/60">{Number(available || 0).toLocaleString('pt-BR')}</td><td className="px-4 py-4 text-right text-white/45">{Number(item.minimum_quantity || 0).toLocaleString('pt-BR')}</td><td className="px-4 py-4 text-right text-white/75">{money(item.average_cost)}</td><td className="px-4 py-4 text-white/45">{item.storage_location || '—'}</td><td className="px-5 py-4"><div className="flex flex-wrap gap-1"><Button size="sm" variant="outline" onClick={() => openOperation('adjust_in', item.id)} className="border-white/10">Ajustar</Button><Button size="sm" variant="ghost" onClick={() => openOperation('loss', item.id)} className="text-amber-300"><PackageMinus className="h-3.5 w-3.5" /></Button><Button size="sm" variant="ghost" onClick={() => openOperation('transfer', item.id)} className="text-sky-300"><ArrowLeftRight className="h-3.5 w-3.5" /></Button><Badge variant="outline" className={isLow ? 'border-amber-500/30 text-amber-200' : 'border-emerald-500/30 text-emerald-300'}>{isLow ? 'Repor' : 'Normal'}</Badge></div></td></tr>; })}</tbody></table></div>{scopedStock.length === 0 && <div className="py-12 text-center text-sm text-white/35">Nenhum insumo encontrado.</div>}</div>
        <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><div className="rounded-3xl border border-white/10 bg-white/[0.03] p-5"><h3 className="font-semibold text-white">Últimas compras</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{scopedDocuments.slice(0, 6).map((document) => <div key={document.id} className="rounded-2xl border border-white/10 bg-black/15 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium text-white">{document.supplier_name || 'Fornecedor a revisar'}</p><p className="mt-1 text-xs text-white/35">{document.document_number || document.id.slice(0, 8)} · {date(document.issue_date)}</p></div><Badge variant="outline" className="border-white/10 text-white/50">{document.status}</Badge></div><p className="mt-2 text-right font-semibold text-orange-300">{money(document.total)}</p></div>)}{scopedDocuments.length === 0 && <p className="py-8 text-center text-sm text-white/35">Nenhuma nota processada.</p>}</div></div><div className="rounded-3xl border border-white/10 bg-white/[0.03] p-5"><div className="flex items-center gap-2"><Truck className="h-5 w-5 text-sky-300" /><h3 className="font-semibold text-white">Fornecedores</h3></div><p className="mt-3 text-3xl font-bold text-white">{suppliers.length}</p><p className="text-sm text-white/40">Parceiros cadastrados e avaliáveis.</p></div></div>
      </TabsContent>
      <TabsContent value="lots"><div className="overflow-hidden rounded-3xl border border-white/10 bg-white/[0.03]"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-black/15 text-xs uppercase text-white/35"><tr><th className="px-5 py-3">Insumo/lote</th><th className="px-4 py-3 text-right">Saldo</th><th className="px-4 py-3">Validade</th><th className="px-4 py-3 text-right">Custo</th><th className="px-4 py-3">Armazenagem</th><th className="px-5 py-3">Situação</th></tr></thead><tbody className="divide-y divide-white/5">{scopedLots.map((lot) => { const expired = lot.expiry_date && Date.parse(lot.expiry_date) < Date.now(); const near = !expired && lot.expiry_date && Date.parse(lot.expiry_date) < Date.now() + 30 * 86400000; return <tr key={lot.id}><td className="px-5 py-4"><p className="font-medium text-white">{stockMap[lot.stock_item_id]?.name || lot.stock_item_id}</p><p className="text-xs text-white/35">{lot.lot_number}</p></td><td className="px-4 py-4 text-right text-white/70">{lot.current_quantity} {stockMap[lot.stock_item_id]?.base_unit}</td><td className={`px-4 py-4 ${expired ? 'text-red-300' : near ? 'text-amber-300' : 'text-white/50'}`}>{date(lot.expiry_date)}</td><td className="px-4 py-4 text-right text-white/70">{money(lot.unit_cost)}</td><td className="px-4 py-4 text-white/45">{lot.storage_location || '—'}</td><td className="px-5 py-4"><Badge variant="outline" className={expired || near ? 'border-amber-500/30 text-amber-200' : 'border-white/10 text-white/50'}>{expired ? 'Vencido' : near ? 'A vencer' : lot.status}</Badge></td></tr>; })}</tbody></table></div>{scopedLots.length === 0 && <div className="py-12 text-center text-sm text-white/35">Nenhum lote registrado.</div>}</div></TabsContent>
      <TabsContent value="movements"><div className="overflow-hidden rounded-3xl border border-white/10 bg-white/[0.03]"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-black/15 text-xs uppercase text-white/35"><tr><th className="px-5 py-3">Data</th><th className="px-4 py-3">Insumo</th><th className="px-4 py-3">Movimento</th><th className="px-4 py-3 text-right">Quantidade</th><th className="px-4 py-3 text-right">Após</th><th className="px-5 py-3">Motivo</th></tr></thead><tbody className="divide-y divide-white/5">{scopedMovements.slice(0, 500).map((movement) => <tr key={movement.id}><td className="px-5 py-4 text-white/45">{movement.occurred_at ? new Date(movement.occurred_at).toLocaleString('pt-BR') : '—'}</td><td className="px-4 py-4 font-medium text-white">{stockMap[movement.stock_item_id]?.name || movement.stock_item_id}</td><td className="px-4 py-4"><Badge variant="outline" className="border-white/10 text-white/55">{MOVEMENT_LABEL[movement.movement_type] || movement.movement_type}</Badge></td><td className="px-4 py-4 text-right text-white/70">{movement.quantity}</td><td className="px-4 py-4 text-right text-white/55">{movement.balance_after}</td><td className="px-5 py-4 text-white/45">{movement.reason || '—'}</td></tr>)}</tbody></table></div>{scopedMovements.length === 0 && <div className="py-12 text-center text-sm text-white/35">Nenhum movimento registrado.</div>}</div></TabsContent>
      <TabsContent value="inventory"><InventoryCountPanel counts={inventoryCounts} stockItems={stockItems} selectedUnitId={selectedUnitId} onRefresh={onRefresh} /></TabsContent>
      <TabsContent value="recipes"><ConsumptionRecipesPanel recipes={recipes} stockItems={stockItems} services={services} machines={machines} selectedUnitId={selectedUnitId} onRefresh={onRefresh} /></TabsContent>
    </Tabs>
    <StockOperationDialog open={operationOpen} onOpenChange={setOperationOpen} stockItems={stockItems} units={units} selectedUnitId={selectedUnitId} batches={batches} initialAction={operationAction} initialItemId={operationItemId} onCompleted={onRefresh} />
  </section>;
}
