import { useMemo, useState } from 'react';
import { CalendarClock, Check, Loader2, Plus, Search } from 'lucide-react';
import { toast } from 'sonner';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';

const STAGES = { washing: 'Lavagem', drying: 'Secagem', dry_cleaning: 'Lavagem a seco', ironing: 'Passadoria', finishing: 'Finalização', quality_control: 'Qualidade', packaging: 'Embalagem' };
const MACHINE_TYPE = { washing: 'wash', drying: 'dry', dry_cleaning: 'dry_clean', ironing: 'iron', finishing: 'finishing', quality_control: 'quality', packaging: 'packaging' };

export default function ProductionBatchDialog({ open, onOpenChange, garments = [], customers = [], machines = [], recipes = [], unitId, onCreated }) {
  const [busy, setBusy] = useState(false);
  const [search, setSearch] = useState('');
  const [form, setForm] = useState({ stage: 'washing', machine_id: '', recipe_id: '', garment_item_ids: [], total_weight_kg: '', priority: 'normal', estimated_minutes: '', scheduled_at: '', notes: '', capacity_override: false, capacity_override_reason: '' });
  const customerMap = useMemo(() => Object.fromEntries(customers.map((customer) => [customer.id, customer.full_name])), [customers]);
  const eligible = useMemo(() => garments.filter((garment) => garment.unit_id === unitId && !garment.current_production_batch_id && !['delivered', 'cancelled', 'out_for_delivery', 'draft', 'awaiting_approval'].includes(garment.status) && `${garment.garment_code} ${garment.product_name} ${garment.ticket_number} ${customerMap[garment.customer_id]}`.toLowerCase().includes(search.toLowerCase())), [garments, unitId, search, customerMap]);
  const compatibleMachines = machines.filter((machine) => (!machine.unit_id || machine.unit_id === unitId) && machine.active !== false && machine.machine_type === MACHINE_TYPE[form.stage]);
  const compatibleRecipes = recipes.filter((recipe) => recipe.unit_id === unitId && recipe.active !== false && recipe.stage === form.stage);
  const selected = garments.filter((garment) => form.garment_item_ids.includes(garment.id));
  const totalWeight = form.total_weight_kg === '' ? selected.reduce((sum, garment) => sum + Number(garment.actual_weight_kg || garment.estimated_weight_kg || 0), 0) : Number(form.total_weight_kg);
  const machine = compatibleMachines.find((item) => item.machine_id === form.machine_id);
  const weightPercent = machine?.capacity_kg ? (totalWeight / Number(machine.capacity_kg)) * 100 : 0;
  const itemPercent = machine?.capacity_items ? (selected.length / Number(machine.capacity_items)) * 100 : 0;
  const capacityPercent = Math.max(weightPercent, itemPercent, 0);
  const toggle = (id) => setForm((state) => ({ ...state, garment_item_ids: state.garment_item_ids.includes(id) ? state.garment_item_ids.filter((value) => value !== id) : [...state.garment_item_ids, id] }));

  const submit = async () => {
    if (!unitId) return toast.error('Selecione uma unidade específica.');
    if (form.garment_item_ids.length === 0) return toast.error('Selecione pelo menos uma peça.');
    if (capacityPercent > Number(machine?.maximum_load_percent || 100) && (!form.capacity_override || !form.capacity_override_reason.trim())) return toast.error('A carga excede a capacidade. Informe a autorização e o motivo.');
    setBusy(true);
    try {
      await base44.functions.invoke('manage_production_batch', { action: 'create', unit_id: unitId, ...form, machine_id: form.machine_id || undefined, recipe_id: form.recipe_id || undefined, total_weight_kg: totalWeight, estimated_minutes: Number(form.estimated_minutes || 0), scheduled_at: form.scheduled_at ? new Date(form.scheduled_at).toISOString() : undefined, idempotency_key: crypto.randomUUID() });
      toast.success('Lote de produção criado.'); onOpenChange(false); onCreated?.();
    } catch (error) { console.error(error); toast.error('Não foi possível criar o lote. Verifique capacidade, peças e insumos.'); }
    finally { setBusy(false); }
  };

  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-5xl border-white/10 bg-[#160d29] text-white"><DialogHeader><DialogTitle>Novo lote de produção</DialogTitle><DialogDescription className="text-white/45">Agrupe peças compatíveis, valide capacidade e associe a ficha de consumo.</DialogDescription></DialogHeader><div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]">
    <div className="space-y-3"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-white/35" /><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar peça, ticket ou cliente" className="border-white/10 bg-white/5 pl-9" /></div><div className="max-h-[470px] space-y-2 overflow-auto rounded-2xl border border-white/10 p-3">{eligible.map((garment) => { const active = form.garment_item_ids.includes(garment.id); return <button key={garment.id} type="button" onClick={() => toggle(garment.id)} className={`flex w-full items-center gap-3 rounded-2xl border p-3 text-left transition ${active ? 'border-violet-400 bg-violet-500/15' : 'border-white/10 bg-white/[0.025] hover:bg-white/[0.05]'}`}><span className={`flex h-6 w-6 items-center justify-center rounded-full border ${active ? 'border-violet-300 bg-violet-500' : 'border-white/20'}`}>{active && <Check className="h-3.5 w-3.5" />}</span><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-white">{garment.product_name}</strong><span className="text-xs text-white/40">{garment.garment_code} · {customerMap[garment.customer_id] || 'Cliente'} · {garment.status}</span></span><Badge variant="outline" className="border-white/10 text-white/45">{garment.actual_weight_kg || garment.estimated_weight_kg ? `${garment.actual_weight_kg || garment.estimated_weight_kg} kg` : 'sem peso'}</Badge></button>; })}{eligible.length === 0 && <p className="py-10 text-center text-sm text-white/35">Nenhuma peça elegível.</p>}</div></div>
    <div className="space-y-4 rounded-3xl border border-white/10 bg-white/[0.025] p-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><div><Label>Etapa</Label><select value={form.stage} onChange={(e) => setForm((state) => ({ ...state, stage: e.target.value, machine_id: '', recipe_id: '' }))} className="mt-1 h-10 w-full rounded-md border border-white/10 bg-[#201334] px-3 text-sm">{Object.entries(STAGES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div><Label>Máquina</Label><select value={form.machine_id} onChange={(e) => setForm((state) => ({ ...state, machine_id: e.target.value }))} className="mt-1 h-10 w-full rounded-md border border-white/10 bg-[#201334] px-3 text-sm"><option value="">Sem máquina / etapa manual</option>{compatibleMachines.map((item) => <option key={item.machine_id} value={item.machine_id}>{item.name || item.machine_id} · {item.operational_status || 'idle'}</option>)}</select></div><div><Label>Ficha técnica</Label><select value={form.recipe_id} onChange={(e) => setForm((state) => ({ ...state, recipe_id: e.target.value }))} className="mt-1 h-10 w-full rounded-md border border-white/10 bg-[#201334] px-3 text-sm"><option value="">Sem baixa automática</option>{compatibleRecipes.map((recipe) => <option key={recipe.id} value={recipe.id}>{recipe.name} · v{recipe.version}</option>)}</select></div><div><Label>Peso total (kg)</Label><Input type="number" min="0" step="0.01" value={form.total_weight_kg} onChange={(e) => setForm((state) => ({ ...state, total_weight_kg: e.target.value }))} placeholder={totalWeight ? String(totalWeight) : '0'} className="mt-1 border-white/10 bg-white/5" /></div><div><Label>Duração prevista (min)</Label><Input type="number" min="0" value={form.estimated_minutes} onChange={(e) => setForm((state) => ({ ...state, estimated_minutes: e.target.value }))} className="mt-1 border-white/10 bg-white/5" /></div><div><Label>Prioridade</Label><select value={form.priority} onChange={(e) => setForm((state) => ({ ...state, priority: e.target.value }))} className="mt-1 h-10 w-full rounded-md border border-white/10 bg-[#201334] px-3 text-sm"><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></div><div><Label>Agendar para</Label><Input type="datetime-local" value={form.scheduled_at} onChange={(e) => setForm((state) => ({ ...state, scheduled_at: e.target.value }))} className="mt-1 border-white/10 bg-white/5" /></div></div>
    <div className="rounded-2xl border border-white/10 bg-black/15 p-4"><div className="flex items-center justify-between"><span className="text-sm text-white/50">Carga selecionada</span><strong className="text-white">{selected.length} peças · {totalWeight.toLocaleString('pt-BR')} kg</strong></div>{machine && <><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className={`h-full ${capacityPercent > 100 ? 'bg-red-500' : capacityPercent > 85 ? 'bg-amber-500' : 'bg-emerald-500'}`} style={{ width: `${Math.min(100, capacityPercent)}%` }} /></div><p className="mt-2 text-xs text-white/40">Capacidade utilizada: {capacityPercent.toFixed(1)}%</p></>}{capacityPercent > Number(machine?.maximum_load_percent || 100) && <div className="mt-3 space-y-2 rounded-xl border border-red-500/20 bg-red-500/5 p-3"><label className="flex items-center gap-2 text-sm text-red-200"><input type="checkbox" checked={form.capacity_override} onChange={(e) => setForm((state) => ({ ...state, capacity_override: e.target.checked }))} />Autorizar exceção gerencial</label><Input value={form.capacity_override_reason} onChange={(e) => setForm((state) => ({ ...state, capacity_override_reason: e.target.value }))} placeholder="Motivo obrigatório" className="border-red-500/20 bg-black/15" /></div>}</div>
    <div><Label>Observações</Label><Input value={form.notes} onChange={(e) => setForm((state) => ({ ...state, notes: e.target.value }))} className="mt-1 border-white/10 bg-white/5" /></div></div>
  </div><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => onOpenChange(false)} className="border-white/10">Cancelar</Button><Button onClick={submit} disabled={busy} className="bg-gradient-to-r from-violet-500 to-fuchsia-500">{busy ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : form.scheduled_at ? <CalendarClock className="mr-2 h-4 w-4" /> : <Plus className="mr-2 h-4 w-4" />}Criar lote</Button></div></DialogContent></Dialog>;
}
