import { createClientFromRequest } from 'npm:@base44/sdk@0.8.46';
import { authorizeUserOrInternal, enforceAuthenticatedUser, securityErrorResponse } from '../../shared/functionSecurity.js';
import { allocateLots, moneyRound, quantityRound, weightedAverageCost } from '../../shared/stockMath.js';
import { assertSameCompanyTransfer, quantity } from '../../shared/procurementInventoryCore.js';

function clean(value: unknown, max = 500) { return String(value || '').trim().slice(0, max); }
function reason(value: unknown, min = 8) { const text = clean(value, 1000); if (text.length < min) throw new Error('reason_required'); return text; }
function transferNumber() { return `TE-${new Date().toISOString().replace(/\D/g, '').slice(0, 14)}-${crypto.randomUUID().replace(/-/g, '').slice(0, 6).toUpperCase()}`; }
async function principalFor(base44: any, req: Request, user: any, legalEntityId: string, requireMfa = false) { return enforceAuthenticatedUser(base44, req, user, { permission: 'inventory.transfer', legalEntityId, requireMfa, source: 'manage_stock_transfers' }); }
async function frozen(db: any, legalEntityId: string, warehouseId: string) { const counts = await db.InventoryCount.filter({ legal_entity_id: legalEntityId, warehouse_id: warehouseId }, '-created_date', 100).catch(() => []); if (counts.some((count: any) => count.status === 'counting' && count.freeze_movements === true)) throw Object.assign(new Error('inventory_count_freezes_movements'), { status: 423 }); }
async function audit(db: any, principal: any, transfer: any, action: string, changeReason: string, requestId: string, before: any, after: any) { return db.AuditLog.create({ action, entity_type: 'stock_transfer', entity_id: transfer.id, item_label: transfer.transfer_number, reason: changeReason, user_id: principal.user.id, user_email: principal.user.email, user_name: principal.user.full_name || principal.user.email, user_role: principal.role, legal_entity_id: transfer.legal_entity_id, unit_id: transfer.source_unit_id, request_id: requestId, before_data: before, after_data: after, domain: 'inventory', success: true }); }
async function destinationItem(db: any, source: any, transfer: any) { const matches = await db.StockItem.filter({ legal_entity_id: transfer.legal_entity_id, warehouse_id: transfer.destination_warehouse_id, sku: source.sku }, '-created_date', 5).catch(() => []); if (matches[0]) return matches[0]; return db.StockItem.create({ legal_entity_id: transfer.legal_entity_id, unit_id: transfer.destination_unit_id, warehouse_id: transfer.destination_warehouse_id, catalog_item_id: source.catalog_item_id, cost_center_id: source.cost_center_id, sku: source.sku, name: source.name, description: source.description, category: source.category, base_unit: source.base_unit, purchase_unit: source.purchase_unit, purchase_to_base_factor: source.purchase_to_base_factor || 1, current_quantity: 0, reserved_quantity: 0, available_quantity: 0, minimum_quantity: source.minimum_quantity || 0, maximum_quantity: source.maximum_quantity, reorder_quantity: source.reorder_quantity || 0, reorder_lead_days: source.reorder_lead_days || 0, safety_stock_quantity: source.safety_stock_quantity || 0, average_cost: source.average_cost || 0, last_cost: source.last_cost || 0, preferred_supplier_id: source.preferred_supplier_id, supplier_codes: source.supplier_codes || {}, barcode: source.barcode, storage_location: source.storage_location, abc_class: source.abc_class || 'unclassified', batch_control: source.batch_control || false, expiry_control: source.expiry_control || false, negative_stock_allowed: false, active: true, metadata: { replicated_from_stock_item_id: source.id } }); }
async function createDestinationLot(db: any, destination: any, transfer: any, allocation: any, acceptedQuantity: number, now: string) { const lotNumber = clean(allocation.lot_number || `TRANSFER-${transfer.transfer_number}`, 120); const matches = await db.StockLot.filter({ legal_entity_id: transfer.legal_entity_id, warehouse_id: transfer.destination_warehouse_id, stock_item_id: destination.id, lot_number: lotNumber }, '-created_date', 5).catch(() => []); const lot = matches.find((row: any) => row.status !== 'cancelled'); if (lot) { const before = quantity(lot.current_quantity || 0); const after = quantity(before + acceptedQuantity); const average = weightedAverageCost({ currentQuantity: before, currentAverageCost: lot.unit_cost, incomingQuantity: acceptedQuantity, incomingUnitCost: allocation.unit_cost }); return db.StockLot.update(lot.id, { current_quantity: after, initial_quantity: quantity(Number(lot.initial_quantity || 0) + acceptedQuantity), unit_cost: average, total_cost: moneyRound(after * average), expiry_date: allocation.expiry_date || lot.expiry_date, status: 'available', last_movement_at: now }); } return db.StockLot.create({ legal_entity_id: transfer.legal_entity_id, unit_id: transfer.destination_unit_id, warehouse_id: transfer.destination_warehouse_id, stock_item_id: destination.id, lot_number: lotNumber, received_at: now, expiry_date: allocation.expiry_date, initial_quantity: acceptedQuantity, current_quantity: acceptedQuantity, reserved_quantity: 0, unit_cost: allocation.unit_cost, total_cost: moneyRound(acceptedQuantity * allocation.unit_cost), storage_location: destination.storage_location, status: 'available', quality_status: 'approved', last_movement_at: now, metadata: { stock_transfer_id: transfer.id, source_stock_lot_id: allocation.stock_lot_id } }); }

export default async function(req: Request): Promise<Response> {
  const requestId = crypto.randomUUID();
  try {
    if (req.method !== 'POST') return Response.json({ error: 'method_not_allowed', request_id: requestId }, { status: 405 });
    const base44 = createClientFromRequest(req); const db = base44.asServiceRole.entities; const body = await req.json(); const action = clean(body.action, 50); const auth = await authorizeUserOrInternal(base44, req, body, { allowInternal: false, source: 'manage_stock_transfers' });
    if (action === 'overview') { const legalEntityId = clean(body.legal_entity_id, 100); await principalFor(base44, req, auth.user, legalEntityId); const [transfers, items] = await Promise.all([db.StockTransfer.filter({ legal_entity_id: legalEntityId }, '-created_date', 1000).catch(() => []), db.StockTransferItem.filter({ legal_entity_id: legalEntityId }, '-created_date', 5000).catch(() => [])]); return Response.json({ transfers, items, request_id: requestId }); }
    if (action === 'create') {
      const legalEntityId = clean(body.legal_entity_id, 100); const principal = await principalFor(base44, req, auth.user, legalEntityId); const sourceWarehouse = await db.Warehouse.get(body.source_warehouse_id).catch(() => null); const destinationWarehouse = await db.Warehouse.get(body.destination_warehouse_id).catch(() => null); assertSameCompanyTransfer(sourceWarehouse, destinationWarehouse); if (sourceWarehouse.legal_entity_id !== legalEntityId) return Response.json({ error: 'warehouse_scope_mismatch', request_id: requestId }, { status: 409 });
      const key = clean(body.idempotency_key, 180); if (key.length < 12) return Response.json({ error: 'idempotency_key_required', request_id: requestId }, { status: 422 }); const prior = await db.StockTransfer.filter({ idempotency_key: key }, '-created_date', 3).catch(() => []); if (prior[0]) return Response.json({ stock_transfer: prior[0], duplicate: true, request_id: requestId }); const lines = Array.isArray(body.items) ? body.items : []; if (!lines.length) return Response.json({ error: 'transfer_items_required', request_id: requestId }, { status: 422 });
      for (const line of lines) { const item = await db.StockItem.get(line.stock_item_id).catch(() => null); if (!item || item.legal_entity_id !== legalEntityId || item.warehouse_id !== sourceWarehouse.id || quantity(line.quantity) <= 0) return Response.json({ error: 'stock_item_scope_mismatch', request_id: requestId }, { status: 409 }); }
      const transfer = await db.StockTransfer.create({ legal_entity_id: legalEntityId, source_unit_id: sourceWarehouse.unit_id, source_warehouse_id: sourceWarehouse.id, destination_unit_id: destinationWarehouse.unit_id, destination_warehouse_id: destinationWarehouse.id, transfer_number: transferNumber(), status: 'draft', requested_by_user_id: principal.user.id, reason: reason(body.reason), idempotency_key: key, metadata: {} });
      for (const line of lines) { const item = await db.StockItem.get(line.stock_item_id); await db.StockTransferItem.create({ stock_transfer_id: transfer.id, legal_entity_id: legalEntityId, source_stock_item_id: item.id, stock_lot_id: line.stock_lot_id, requested_quantity: quantity(line.quantity), dispatched_quantity: 0, received_quantity: 0, unit_cost: Number(item.average_cost || 0), line_status: 'requested', metadata: {} }); }
      await audit(db, principal, transfer, 'create', transfer.reason, requestId, null, { status: transfer.status, item_count: lines.length }); return Response.json({ stock_transfer: transfer, request_id: requestId }, { status: 201 });
    }
    const transfer = await db.StockTransfer.get(body.stock_transfer_id).catch(() => null); if (!transfer) return Response.json({ error: 'stock_transfer_not_found', request_id: requestId }, { status: 404 }); const principal = await principalFor(base44, req, auth.user, transfer.legal_entity_id, true); const changeReason = reason(body.reason || transfer.reason);
    if (action === 'approve') { if (transfer.status !== 'draft') return Response.json({ error: 'stock_transfer_not_approvable', request_id: requestId }, { status: 409 }); const updated = await db.StockTransfer.update(transfer.id, { status: 'approved', approved_by_user_id: principal.user.id, approved_at: new Date().toISOString(), reason: changeReason }); await audit(db, principal, transfer, 'approve', changeReason, requestId, { status: transfer.status }, { status: 'approved' }); return Response.json({ stock_transfer: updated, request_id: requestId }); }
    if (action === 'dispatch') {
      if (transfer.status !== 'approved') return Response.json({ error: 'approved_stock_transfer_required', request_id: requestId }, { status: 409 }); await frozen(db, transfer.legal_entity_id, transfer.source_warehouse_id); const lines = await db.StockTransferItem.filter({ stock_transfer_id: transfer.id }, 'created_date', 1000); const completed = [];
      try { for (const line of lines) { const source = await db.StockItem.get(line.source_stock_item_id).catch(() => null); if (!source || source.warehouse_id !== transfer.source_warehouse_id || source.legal_entity_id !== transfer.legal_entity_id) throw new Error('stock_item_scope_mismatch'); const dispatchQuantity = quantity(line.requested_quantity); const before = quantity(source.current_quantity || 0); if (before < dispatchQuantity) throw new Error('insufficient_stock'); let allocations: any[] = []; if (source.batch_control) { const lots = await db.StockLot.filter({ legal_entity_id: transfer.legal_entity_id, warehouse_id: transfer.source_warehouse_id, stock_item_id: source.id }, '-expiry_date', 1000); const allocated = allocateLots(line.stock_lot_id ? lots.filter((lot: any) => lot.id === line.stock_lot_id) : lots, dispatchQuantity); if (allocated.remaining_quantity > 0) throw new Error('insufficient_lot_stock'); allocations = allocated.allocations; for (const part of allocations) await db.StockLot.update(part.stock_lot_id, { current_quantity: part.balance_after, total_cost: moneyRound(part.balance_after * part.unit_cost), status: part.balance_after <= 0 ? 'exhausted' : 'available', last_movement_at: new Date().toISOString() }); }
        const after = quantity(before - dispatchQuantity); const now = new Date().toISOString(); const movement = await db.StockMovement.create({ legal_entity_id: transfer.legal_entity_id, unit_id: transfer.source_unit_id, warehouse_id: transfer.source_warehouse_id, source_warehouse_id: transfer.source_warehouse_id, destination_warehouse_id: transfer.destination_warehouse_id, stock_item_id: source.id, stock_lot_id: line.stock_lot_id, movement_type: 'transfer_out', quantity: dispatchQuantity, unit_cost: Number(source.average_cost || 0), total_cost: moneyRound(dispatchQuantity * Number(source.average_cost || 0)), balance_before: before, balance_after: after, source_unit_id: transfer.source_unit_id, destination_unit_id: transfer.destination_unit_id, transfer_id: transfer.id, operator_user_id: principal.user.id, reason: changeReason, occurred_at: now, request_id: requestId, status: 'posted', metadata: { lot_allocations: allocations } }); await db.StockItem.update(source.id, { current_quantity: after, available_quantity: quantity(after - Number(source.reserved_quantity || 0)), last_movement_at: now }); await db.StockTransferItem.update(line.id, { dispatched_quantity: dispatchQuantity, source_movement_id: movement.id, line_status: 'dispatched', metadata: { ...(line.metadata || {}), lot_allocations: allocations } }); completed.push(line.id); }
        const updated = await db.StockTransfer.update(transfer.id, { status: 'dispatched', dispatched_by_user_id: principal.user.id, dispatched_at: new Date().toISOString() }); await audit(db, principal, transfer, 'status_change', changeReason, requestId, { status: transfer.status }, { status: 'dispatched', dispatched_lines: completed.length }); return Response.json({ stock_transfer: updated, request_id: requestId });
      } catch (error: any) { await db.RepairTask.create({ legal_entity_id: transfer.legal_entity_id, unit_id: transfer.source_unit_id, domain: 'inventory', entity_type: 'stock_transfer', entity_id: transfer.id, title: 'Reparar expedição de transferência', description: 'A expedição falhou após iniciar movimentos e não deve ser repetida automaticamente.', severity: 'critical', status: 'open', required_permission: 'repairs.manage', checkpoints: completed, context_snapshot: { safe_error_code: clean(error?.message, 120) }, metadata: {} }).catch(() => null); throw Object.assign(new Error('stock_transfer_partial_failure_requires_repair'), { status: 409 }); }
    }
    if (action === 'receive') {
      if (!['dispatched', 'partially_received'].includes(transfer.status)) return Response.json({ error: 'dispatched_stock_transfer_required', request_id: requestId }, { status: 409 }); await frozen(db, transfer.legal_entity_id, transfer.destination_warehouse_id); const eventKey = `stock_transfer_receive:${transfer.id}:${clean(body.idempotency_key, 180)}`; if (!body.idempotency_key || clean(body.idempotency_key, 180).length < 12) return Response.json({ error: 'idempotency_key_required', request_id: requestId }, { status: 422 }); const events = await db.ProcessedEvent.filter({ event_key: eventKey }, '-created_date', 3).catch(() => []); if (events.some((event: any) => event.status === 'completed')) return Response.json({ duplicate: true, result: events.find((event: any) => event.status === 'completed').result, request_id: requestId }); const lines = await db.StockTransferItem.filter({ stock_transfer_id: transfer.id }, 'created_date', 1000); const requests = Array.isArray(body.items) && body.items.length ? body.items : lines.map((line: any) => ({ stock_transfer_item_id: line.id, received_quantity: quantity(line.dispatched_quantity - line.received_quantity) })); const checkpoint = events[0] || await db.ProcessedEvent.create({ event_key: eventKey, event_type: 'stock_transfer_received', source: 'user_command', status: 'processing', attempts: 1, started_at: new Date().toISOString(), unit_id: transfer.destination_unit_id, legal_entity_id: transfer.legal_entity_id }); const completed = [];
      try { for (const input of requests) { const line = lines.find((item: any) => item.id === input.stock_transfer_item_id); if (!line) throw new Error('stock_transfer_item_not_found'); const receiveQuantity = quantity(input.received_quantity); const openQuantity = quantity(line.dispatched_quantity - line.received_quantity); if (receiveQuantity <= 0 || receiveQuantity > openQuantity) throw new Error('invalid_received_quantity'); const source = await db.StockItem.get(line.source_stock_item_id); const destination = await destinationItem(db, source, transfer); const before = quantity(destination.current_quantity || 0); const after = quantity(before + receiveQuantity); const now = new Date().toISOString(); const average = weightedAverageCost({ currentQuantity: before, currentAverageCost: destination.average_cost, incomingQuantity: receiveQuantity, incomingUnitCost: line.unit_cost }); const allocations = line.metadata?.lot_allocations || []; if (source.batch_control && allocations.length) { let remaining = receiveQuantity; for (const allocation of allocations) { if (remaining <= 0) break; const accepted = Math.min(remaining, Number(allocation.quantity || 0)); if (accepted > 0) await createDestinationLot(db, destination, transfer, allocation, accepted, now); remaining = quantity(remaining - accepted); } }
        const movement = await db.StockMovement.create({ legal_entity_id: transfer.legal_entity_id, unit_id: transfer.destination_unit_id, warehouse_id: transfer.destination_warehouse_id, source_warehouse_id: transfer.source_warehouse_id, destination_warehouse_id: transfer.destination_warehouse_id, stock_item_id: destination.id, movement_type: 'transfer_in', quantity: receiveQuantity, unit_cost: Number(line.unit_cost || source.average_cost || 0), total_cost: moneyRound(receiveQuantity * Number(line.unit_cost || source.average_cost || 0)), balance_before: before, balance_after: after, source_unit_id: transfer.source_unit_id, destination_unit_id: transfer.destination_unit_id, transfer_id: transfer.id, operator_user_id: principal.user.id, reason: changeReason, occurred_at: now, request_id: requestId, status: 'posted' }); await db.StockItem.update(destination.id, { current_quantity: after, available_quantity: quantity(after - Number(destination.reserved_quantity || 0)), average_cost: average, last_cost: Number(line.unit_cost || 0), last_movement_at: now }); const receivedTotal = quantity(Number(line.received_quantity || 0) + receiveQuantity); await db.StockTransferItem.update(line.id, { destination_stock_item_id: destination.id, received_quantity: receivedTotal, destination_movement_id: movement.id, line_status: receivedTotal >= Number(line.dispatched_quantity || 0) ? 'received' : 'partially_received' }); completed.push(line.id); }
        const refreshed = await db.StockTransferItem.filter({ stock_transfer_id: transfer.id }, 'created_date', 1000); const complete = refreshed.every((line: any) => Number(line.received_quantity || 0) >= Number(line.dispatched_quantity || 0)); const updated = await db.StockTransfer.update(transfer.id, { status: complete ? 'received' : 'partially_received', received_by_user_id: complete ? principal.user.id : transfer.received_by_user_id, received_at: complete ? new Date().toISOString() : transfer.received_at }); const result = { stock_transfer_id: transfer.id, status: updated.status, received_lines: completed.length }; await db.ProcessedEvent.update(checkpoint.id, { status: 'completed', entity_type: 'stock_transfer', entity_id: transfer.id, result, completed_at: new Date().toISOString() }); await audit(db, principal, transfer, 'status_change', changeReason, requestId, { status: transfer.status }, { status: updated.status, received_lines: completed.length }); return Response.json({ stock_transfer: updated, result, request_id: requestId });
      } catch (error: any) { await db.RepairTask.create({ legal_entity_id: transfer.legal_entity_id, unit_id: transfer.destination_unit_id, domain: 'inventory', entity_type: 'stock_transfer', entity_id: transfer.id, title: 'Reparar recebimento de transferência', description: 'O recebimento falhou após iniciar movimentos e não deve ser repetido automaticamente.', severity: 'critical', status: 'open', required_permission: 'repairs.manage', checkpoints: completed, context_snapshot: { safe_error_code: clean(error?.message, 120), processed_event_id: checkpoint.id }, metadata: {} }).catch(() => null); throw Object.assign(new Error('stock_transfer_receive_partial_failure_requires_repair'), { status: 409 }); }
    }
    return Response.json({ error: 'unsupported_action', request_id: requestId }, { status: 400 });
  } catch (error: any) { if (error?.name === 'SecurityError') return securityErrorResponse(error); const status = Number(error?.status || (['reason_required', 'invalid_quantity', 'invalid_transfer_warehouses', 'intercompany_stock_transfer_requires_separate_process', 'warehouse_not_active'].includes(error?.message) ? 422 : 500)); return Response.json({ error: clean(error?.message || 'stock_transfer_failed', 120), request_id: requestId }, { status }); }
}
