import { createClientFromRequest } from 'npm:@base44/sdk@0.8.46';
import { authorizeUserOrInternal, enforceAuthenticatedUser, securityErrorResponse } from '../../shared/functionSecurity.js';
import { assertWarehouseScope, computePurchaseTotals, money, purchaseOrderTransition, purchaseRequisitionTransition, quantity, receiptLineStatus, receiptStatus } from '../../shared/procurementInventoryCore.js';
import { weightedAverageCost } from '../../shared/stockMath.js';

function clean(value: unknown, max = 500) { return String(value || '').trim().slice(0, max); }
function justification(value: unknown, min = 8) { const text = clean(value, 1000); if (text.length < min) throw new Error('reason_required'); return text; }
function number(prefix: string) { return `${prefix}-${new Date().toISOString().replace(/\D/g, '').slice(0, 14)}-${crypto.randomUUID().replace(/-/g, '').slice(0, 6).toUpperCase()}`; }
async function principalFor(base44: any, req: Request, user: any, permission: string, legalEntityId: string, requireMfa = false) { return enforceAuthenticatedUser(base44, req, user, { permission, legalEntityId, requireMfa, source: 'manage_procurement_core' }); }
async function warehouseFor(db: any, warehouseId: string, legalEntityId: string, unitId?: string) { const warehouse = await db.Warehouse.get(warehouseId).catch(() => null); assertWarehouseScope({ warehouse, legalEntityId, unitId }); return warehouse; }
async function audit(db: any, principal: any, input: any) { return db.AuditLog.create({ action: input.action, entity_type: input.entity_type, entity_id: input.entity_id, item_label: input.item_label, amount: input.amount, reason: input.reason, user_id: principal.user.id, user_email: principal.user.email, user_name: principal.user.full_name || principal.user.email, user_role: principal.role, legal_entity_id: input.legal_entity_id, unit_id: input.unit_id, request_id: input.request_id, before_data: input.before_data, after_data: input.after_data, metadata: input.metadata || {}, domain: 'inventory', success: true }); }
async function getByIdempotency(db: any, entity: string, key: string) { const rows = await db[entity].filter({ idempotency_key: key }, '-created_date', 3).catch(() => []); return rows[0] || null; }
async function freezeCheck(db: any, legalEntityId: string, warehouseId: string) { const counts = await db.InventoryCount.filter({ legal_entity_id: legalEntityId, warehouse_id: warehouseId }, '-created_date', 100).catch(() => []); if (counts.some((row: any) => row.status === 'counting' && row.freeze_movements === true)) throw Object.assign(new Error('inventory_count_freezes_movements'), { status: 423 }); }
async function receiveStock(db: any, principal: any, receipt: any, line: any, orderItem: any, requestId: string) {
  const stockItem = await db.StockItem.get(line.stock_item_id).catch(() => null);
  if (!stockItem || stockItem.legal_entity_id !== receipt.legal_entity_id || stockItem.warehouse_id !== receipt.warehouse_id || stockItem.unit_id !== receipt.unit_id) throw new Error('stock_item_scope_mismatch');
  const accepted = quantity(line.accepted_quantity); const factor = Math.max(0.000001, quantity(line.conversion_factor || orderItem.conversion_factor || stockItem.purchase_to_base_factor || 1)); const baseQuantity = quantity(accepted * factor); const unitCost = money((line.unit_price ?? orderItem.unit_price ?? 0) / factor); const before = quantity(stockItem.current_quantity || 0); const after = quantity(before + baseQuantity); const now = new Date().toISOString();
  let lot = null;
  if (baseQuantity > 0 && (stockItem.batch_control || stockItem.expiry_control || line.batch_number || line.expiry_date)) {
    const lotNumber = clean(line.batch_number || `GR-${receipt.receipt_number}-${orderItem.id.slice(0, 6)}`, 120);
    const matches = await db.StockLot.filter({ legal_entity_id: receipt.legal_entity_id, warehouse_id: receipt.warehouse_id, stock_item_id: stockItem.id, lot_number: lotNumber }, '-created_date', 5).catch(() => []); lot = matches.find((item: any) => item.status !== 'cancelled') || null;
    if (lot) { const lotBefore = quantity(lot.current_quantity || 0); const lotAfter = quantity(lotBefore + baseQuantity); const average = weightedAverageCost({ currentQuantity: lotBefore, currentAverageCost: lot.unit_cost, incomingQuantity: baseQuantity, incomingUnitCost: unitCost }); lot = await db.StockLot.update(lot.id, { current_quantity: lotAfter, initial_quantity: quantity(Number(lot.initial_quantity || 0) + baseQuantity), unit_cost: average, total_cost: money(lotAfter * average), expiry_date: line.expiry_date || lot.expiry_date, last_movement_at: now, status: 'available' }); }
    else lot = await db.StockLot.create({ legal_entity_id: receipt.legal_entity_id, unit_id: receipt.unit_id, warehouse_id: receipt.warehouse_id, stock_item_id: stockItem.id, lot_number: lotNumber, supplier_id: receipt.supplier_id, purchase_document_id: receipt.purchase_document_id, purchase_item_id: line.purchase_item_id, goods_receipt_id: receipt.id, goods_receipt_item_id: line.id, received_at: now, expiry_date: line.expiry_date, initial_quantity: baseQuantity, current_quantity: baseQuantity, reserved_quantity: 0, unit_cost: unitCost, total_cost: money(baseQuantity * unitCost), storage_location: stockItem.storage_location, status: 'available', quality_status: line.quality_status === 'pending' ? 'quarantine' : 'approved', last_movement_at: now });
  }
  if (baseQuantity <= 0) return { stockItem, movement: null, baseQuantity };
  const averageCost = weightedAverageCost({ currentQuantity: before, currentAverageCost: stockItem.average_cost, incomingQuantity: baseQuantity, incomingUnitCost: unitCost });
  const movement = await db.StockMovement.create({ legal_entity_id: receipt.legal_entity_id, unit_id: receipt.unit_id, warehouse_id: receipt.warehouse_id, stock_item_id: stockItem.id, stock_lot_id: lot?.id, movement_type: 'purchase_entry', quantity: baseQuantity, unit_cost: unitCost, total_cost: money(baseQuantity * unitCost), balance_before: before, balance_after: after, purchase_order_id: receipt.purchase_order_id, goods_receipt_id: receipt.id, goods_receipt_item_id: line.id, purchase_document_id: receipt.purchase_document_id, purchase_item_id: line.purchase_item_id, batch_number: lot?.lot_number || line.batch_number, expiry_date: lot?.expiry_date || line.expiry_date, operator_user_id: principal.user.id, reason: 'goods_receipt_accepted', occurred_at: now, request_id: requestId, status: 'posted' });
  await db.StockItem.update(stockItem.id, { current_quantity: after, available_quantity: quantity(after - Number(stockItem.reserved_quantity || 0)), average_cost: averageCost, last_cost: unitCost, last_movement_at: now });
  return { stockItem, movement, baseQuantity };
}

export default async function(req: Request): Promise<Response> {
  const requestId = crypto.randomUUID();
  try {
    if (req.method !== 'POST') return Response.json({ error: 'method_not_allowed', request_id: requestId }, { status: 405 });
    const base44 = createClientFromRequest(req); const db = base44.asServiceRole.entities; const body = await req.json(); const action = clean(body.action, 60);
    const auth = await authorizeUserOrInternal(base44, req, body, { allowInternal: false, source: 'manage_procurement_core' });

    if (action === 'overview') {
      const legalEntityId = clean(body.legal_entity_id, 100); await principalFor(base44, req, auth.user, 'purchases.view', legalEntityId);
      const [requisitions, requisitionItems, orders, orderItems, receipts, receiptItems, suppliers, warehouses, stockItems, lots, documents] = await Promise.all([
        db.PurchaseRequisition.filter({ legal_entity_id: legalEntityId }, '-created_date', 1000).catch(() => []), db.PurchaseRequisitionItem.filter({ legal_entity_id: legalEntityId }, '-created_date', 5000).catch(() => []), db.PurchaseOrder.filter({ legal_entity_id: legalEntityId }, '-created_date', 1000).catch(() => []), db.PurchaseOrderItem.filter({ legal_entity_id: legalEntityId }, '-created_date', 5000).catch(() => []), db.GoodsReceipt.filter({ legal_entity_id: legalEntityId }, '-created_date', 1000).catch(() => []), db.GoodsReceiptItem.filter({ legal_entity_id: legalEntityId }, '-created_date', 5000).catch(() => []), db.Supplier.filter({ legal_entity_id: legalEntityId }, 'name', 2000).catch(() => []), db.Warehouse.filter({ legal_entity_id: legalEntityId }, 'name', 1000).catch(() => []), db.StockItem.filter({ legal_entity_id: legalEntityId }, 'name', 5000).catch(() => []), db.StockLot.filter({ legal_entity_id: legalEntityId }, '-received_at', 5000).catch(() => []), db.PurchaseDocument.filter({ legal_entity_id: legalEntityId }, '-created_date', 1000).catch(() => []),
      ]);
      return Response.json({ requisitions, requisition_items: requisitionItems, purchase_orders: orders, purchase_order_items: orderItems, receipts, receipt_items: receiptItems, suppliers, warehouses, stock_items: stockItems, stock_lots: lots, purchase_documents: documents, request_id: requestId });
    }

    if (action === 'create_requisition') {
      const legalEntityId = clean(body.legal_entity_id, 100); const unitId = clean(body.unit_id, 100); const warehouseId = clean(body.warehouse_id, 100); const principal = await principalFor(base44, req, auth.user, 'purchases.manage', legalEntityId); await warehouseFor(db, warehouseId, legalEntityId, unitId);
      const key = clean(body.idempotency_key, 180); if (key.length < 12) return Response.json({ error: 'idempotency_key_required', request_id: requestId }, { status: 422 }); const prior = await getByIdempotency(db, 'PurchaseRequisition', key); if (prior) return Response.json({ purchase_requisition: prior, duplicate: true, request_id: requestId });
      const items = Array.isArray(body.items) ? body.items : []; if (!items.length) return Response.json({ error: 'requisition_items_required', request_id: requestId }, { status: 422 });
      for (const item of items) { if (quantity(item.requested_quantity) <= 0 || !clean(item.description || item.stock_item_name, 300)) return Response.json({ error: 'invalid_requisition_item', request_id: requestId }, { status: 422 }); if (item.stock_item_id) { const stock = await db.StockItem.get(item.stock_item_id).catch(() => null); if (!stock || stock.legal_entity_id !== legalEntityId || stock.warehouse_id !== warehouseId) return Response.json({ error: 'stock_item_scope_mismatch', request_id: requestId }, { status: 409 }); } }
      const totals = computePurchaseTotals(items.map((item: any) => ({ requested_quantity: item.requested_quantity, estimated_unit_price: item.estimated_unit_price })));
      const requisition = await db.PurchaseRequisition.create({ legal_entity_id: legalEntityId, unit_id: unitId, warehouse_id: warehouseId, cost_center_id: clean(body.cost_center_id, 100), request_number: number('SC'), requester_user_id: principal.user.id, needed_by: body.needed_by, priority: ['low', 'normal', 'high', 'urgent'].includes(body.priority) ? body.priority : 'normal', status: 'submitted', estimated_total: totals.total, idempotency_key: key, notes: clean(body.notes, 1000), metadata: {} });
      for (const item of items) await db.PurchaseRequisitionItem.create({ purchase_requisition_id: requisition.id, legal_entity_id: legalEntityId, unit_id: unitId, warehouse_id: warehouseId, stock_item_id: item.stock_item_id, description: clean(item.description || item.stock_item_name, 300), requested_quantity: quantity(item.requested_quantity), approved_quantity: 0, ordered_quantity: 0, purchase_unit: clean(item.purchase_unit || 'unit', 40), estimated_unit_price: money(item.estimated_unit_price || 0), preferred_supplier_id: item.preferred_supplier_id, needed_by: item.needed_by || body.needed_by, line_status: 'requested', notes: clean(item.notes, 500), metadata: {} });
      await audit(db, principal, { action: 'create', entity_type: 'purchase_requisition', entity_id: requisition.id, item_label: requisition.request_number, amount: totals.total, reason: justification(body.reason), legal_entity_id: legalEntityId, unit_id: unitId, request_id: requestId, after_data: { status: requisition.status, item_count: items.length } });
      return Response.json({ purchase_requisition: requisition, request_id: requestId }, { status: 201 });
    }

    if (action === 'approve_requisition' || action === 'reject_requisition') {
      const requisition = await db.PurchaseRequisition.get(body.purchase_requisition_id).catch(() => null); if (!requisition) return Response.json({ error: 'purchase_requisition_not_found', request_id: requestId }, { status: 404 }); const principal = await principalFor(base44, req, auth.user, 'purchases.approve', requisition.legal_entity_id, true); const operation = action === 'approve_requisition' ? 'approve' : 'reject'; const next = purchaseRequisitionTransition(requisition.status, operation); const changeReason = justification(body.reason, 10); const lines = await db.PurchaseRequisitionItem.filter({ purchase_requisition_id: requisition.id }, 'created_date', 1000);
      for (const line of lines) await db.PurchaseRequisitionItem.update(line.id, { approved_quantity: operation === 'approve' ? quantity(body.approved_quantities?.[line.id] ?? line.requested_quantity) : 0, line_status: operation === 'approve' ? 'approved' : 'rejected' });
      const updated = await db.PurchaseRequisition.update(requisition.id, { status: next, approved_by_user_id: operation === 'approve' ? principal.user.id : null, approved_at: operation === 'approve' ? new Date().toISOString() : null, approval_reason: changeReason });
      await audit(db, principal, { action: operation, entity_type: 'purchase_requisition', entity_id: requisition.id, item_label: requisition.request_number, amount: requisition.estimated_total, reason: changeReason, legal_entity_id: requisition.legal_entity_id, unit_id: requisition.unit_id, request_id: requestId, before_data: { status: requisition.status }, after_data: { status: next } }); return Response.json({ purchase_requisition: updated, request_id: requestId });
    }

    if (action === 'create_purchase_order') {
      const requisition = await db.PurchaseRequisition.get(body.purchase_requisition_id).catch(() => null); if (!requisition || requisition.status !== 'approved') return Response.json({ error: 'approved_requisition_required', request_id: requestId }, { status: 409 }); const principal = await principalFor(base44, req, auth.user, 'purchases.manage', requisition.legal_entity_id, true); await warehouseFor(db, requisition.warehouse_id, requisition.legal_entity_id, requisition.unit_id);
      const supplier = await db.Supplier.get(body.supplier_id).catch(() => null); if (!supplier || supplier.legal_entity_id !== requisition.legal_entity_id || supplier.status === 'blocked') return Response.json({ error: 'supplier_scope_mismatch', request_id: requestId }, { status: 409 }); const key = clean(body.idempotency_key, 180); if (key.length < 12) return Response.json({ error: 'idempotency_key_required', request_id: requestId }, { status: 422 }); const prior = await getByIdempotency(db, 'PurchaseOrder', key); if (prior) return Response.json({ purchase_order: prior, duplicate: true, request_id: requestId });
      const requisitionLines = await db.PurchaseRequisitionItem.filter({ purchase_requisition_id: requisition.id }, 'created_date', 1000); const requestedLines = Array.isArray(body.items) && body.items.length ? body.items : requisitionLines.filter((line: any) => line.line_status === 'approved').map((line: any) => ({ requisition_item_id: line.id, stock_item_id: line.stock_item_id, description: line.description, ordered_quantity: line.approved_quantity, purchase_unit: line.purchase_unit, unit_price: line.estimated_unit_price })); if (!requestedLines.length) return Response.json({ error: 'purchase_order_items_required', request_id: requestId }, { status: 422 });
      const totals = computePurchaseTotals(requestedLines, body); const order = await db.PurchaseOrder.create({ legal_entity_id: requisition.legal_entity_id, unit_id: requisition.unit_id, warehouse_id: requisition.warehouse_id, cost_center_id: requisition.cost_center_id, purchase_requisition_id: requisition.id, supplier_id: supplier.id, business_party_id: supplier.business_party_id, order_number: number('PC'), status: 'submitted', currency: 'BRL', ...totals, expected_delivery_at: body.expected_delivery_at, payment_terms: clean(body.payment_terms, 300), buyer_user_id: principal.user.id, idempotency_key: key, notes: clean(body.notes, 1000), metadata: {} });
      for (const item of requestedLines) { const line = item.requisition_item_id ? requisitionLines.find((row: any) => row.id === item.requisition_item_id) : null; if (line && quantity(item.ordered_quantity) > quantity(line.approved_quantity - line.ordered_quantity)) return Response.json({ error: 'ordered_quantity_exceeds_approved', request_id: requestId }, { status: 409 }); const created = await db.PurchaseOrderItem.create({ purchase_order_id: order.id, purchase_requisition_item_id: line?.id, legal_entity_id: order.legal_entity_id, unit_id: order.unit_id, warehouse_id: order.warehouse_id, stock_item_id: item.stock_item_id || line?.stock_item_id, supplier_code: clean(item.supplier_code, 100), description: clean(item.description || line?.description, 300), ordered_quantity: quantity(item.ordered_quantity), received_quantity: 0, accepted_quantity: 0, rejected_quantity: 0, purchase_unit: clean(item.purchase_unit || line?.purchase_unit || 'unit', 40), conversion_factor: Math.max(0.000001, quantity(item.conversion_factor || 1)), unit_price: money(item.unit_price || 0), discount: money(item.discount || 0), taxes: money(item.taxes || 0), total: money(quantity(item.ordered_quantity) * money(item.unit_price || 0) - money(item.discount || 0) + money(item.taxes || 0)), line_status: 'ordered', metadata: {} }); if (line) await db.PurchaseRequisitionItem.update(line.id, { ordered_quantity: quantity(Number(line.ordered_quantity || 0) + created.ordered_quantity), line_status: quantity(Number(line.ordered_quantity || 0) + created.ordered_quantity) >= quantity(line.approved_quantity) ? 'ordered' : 'partially_ordered' }); }
      const allLines = await db.PurchaseRequisitionItem.filter({ purchase_requisition_id: requisition.id }, 'created_date', 1000); const fullyOrdered = allLines.filter((line: any) => line.line_status !== 'rejected').every((line: any) => Number(line.ordered_quantity || 0) >= Number(line.approved_quantity || 0)); await db.PurchaseRequisition.update(requisition.id, { status: fullyOrdered ? 'ordered' : 'partially_ordered' });
      await audit(db, principal, { action: 'create', entity_type: 'purchase_order', entity_id: order.id, item_label: order.order_number, amount: order.total, reason: justification(body.reason), legal_entity_id: order.legal_entity_id, unit_id: order.unit_id, request_id: requestId, after_data: { status: order.status, supplier_id: supplier.id, item_count: requestedLines.length } }); return Response.json({ purchase_order: order, request_id: requestId }, { status: 201 });
    }

    if (['approve_purchase_order', 'reject_purchase_order', 'mark_purchase_order_sent'].includes(action)) {
      const order = await db.PurchaseOrder.get(body.purchase_order_id).catch(() => null); if (!order) return Response.json({ error: 'purchase_order_not_found', request_id: requestId }, { status: 404 }); const permission = action === 'mark_purchase_order_sent' ? 'purchases.manage' : 'purchases.approve'; const principal = await principalFor(base44, req, auth.user, permission, order.legal_entity_id, true); const operation = action === 'approve_purchase_order' ? 'approve' : action === 'reject_purchase_order' ? 'cancel' : 'send'; const next = purchaseOrderTransition(order.status, operation); const changeReason = justification(body.reason, 10); const patch: any = { status: next, approval_reason: changeReason }; if (operation === 'approve') { patch.approved_by_user_id = principal.user.id; patch.approved_at = new Date().toISOString(); } if (operation === 'send') patch.sent_at = new Date().toISOString(); const updated = await db.PurchaseOrder.update(order.id, patch); await audit(db, principal, { action: operation === 'approve' ? 'approve' : operation === 'cancel' ? 'reject' : 'status_change', entity_type: 'purchase_order', entity_id: order.id, item_label: order.order_number, amount: order.total, reason: changeReason, legal_entity_id: order.legal_entity_id, unit_id: order.unit_id, request_id: requestId, before_data: { status: order.status }, after_data: { status: next } }); return Response.json({ purchase_order: updated, request_id: requestId });
    }

    if (action === 'receive_purchase_order') {
      const order = await db.PurchaseOrder.get(body.purchase_order_id).catch(() => null); if (!order || !['sent', 'partially_received'].includes(order.status)) return Response.json({ error: 'sent_purchase_order_required', request_id: requestId }, { status: 409 }); const principal = await principalFor(base44, req, auth.user, 'receipts.manage', order.legal_entity_id); await warehouseFor(db, order.warehouse_id, order.legal_entity_id, order.unit_id); await freezeCheck(db, order.legal_entity_id, order.warehouse_id);
      const key = clean(body.idempotency_key, 180); if (key.length < 12) return Response.json({ error: 'idempotency_key_required', request_id: requestId }, { status: 422 }); const prior = await getByIdempotency(db, 'GoodsReceipt', key); if (prior) { if (['accepted', 'partially_accepted', 'rejected'].includes(prior.status)) return Response.json({ goods_receipt: prior, duplicate: true, request_id: requestId }); return Response.json({ error: 'receipt_requires_repair', goods_receipt_id: prior.id, request_id: requestId }, { status: 409 }); }
      const orderItems = await db.PurchaseOrderItem.filter({ purchase_order_id: order.id }, 'created_date', 1000); const lines = Array.isArray(body.items) ? body.items : []; if (!lines.length) return Response.json({ error: 'receipt_items_required', request_id: requestId }, { status: 422 });
      for (const line of lines) { const orderItem = orderItems.find((row: any) => row.id === line.purchase_order_item_id); if (!orderItem) return Response.json({ error: 'purchase_order_item_not_found', request_id: requestId }, { status: 404 }); const remaining = quantity(orderItem.ordered_quantity - orderItem.received_quantity); if (quantity(line.received_quantity) > remaining) return Response.json({ error: 'received_quantity_exceeds_open_order', request_id: requestId }, { status: 409 }); receiptLineStatus({ received: line.received_quantity, accepted: line.accepted_quantity, rejected: line.rejected_quantity }); }
      const receipt = await db.GoodsReceipt.create({ legal_entity_id: order.legal_entity_id, unit_id: order.unit_id, warehouse_id: order.warehouse_id, purchase_order_id: order.id, purchase_document_id: body.purchase_document_id, supplier_id: order.supplier_id, receipt_number: number('RM'), status: 'receiving', received_at: new Date().toISOString(), receiver_user_id: principal.user.id, quality_status: body.quality_required ? 'pending' : 'not_required', document_asset_ids: body.document_asset_ids || [], divergence_summary: clean(body.divergence_summary, 1000), idempotency_key: key, notes: clean(body.notes, 1000), metadata: {} });
      const results = [];
      try {
        for (const input of lines) { const orderItem = orderItems.find((row: any) => row.id === input.purchase_order_item_id); const lineStatus = receiptLineStatus({ received: input.received_quantity, accepted: input.accepted_quantity, rejected: input.rejected_quantity }); const created = await db.GoodsReceiptItem.create({ goods_receipt_id: receipt.id, purchase_order_item_id: orderItem.id, legal_entity_id: order.legal_entity_id, unit_id: order.unit_id, warehouse_id: order.warehouse_id, stock_item_id: input.stock_item_id || orderItem.stock_item_id, description: orderItem.description, received_quantity: quantity(input.received_quantity), accepted_quantity: quantity(input.accepted_quantity), rejected_quantity: quantity(input.rejected_quantity), base_quantity: 0, purchase_unit: orderItem.purchase_unit, conversion_factor: Number(input.conversion_factor || orderItem.conversion_factor || 1), unit_price: money(orderItem.unit_price), batch_number: clean(input.batch_number, 120), expiry_date: input.expiry_date, quality_status: body.quality_required ? 'pending' : 'approved', divergence_reason: clean(input.divergence_reason, 500), line_status: lineStatus, metadata: {} }); const stockResult = await receiveStock(db, principal, receipt, created, orderItem, requestId); await db.GoodsReceiptItem.update(created.id, { base_quantity: stockResult.baseQuantity, stock_movement_id: stockResult.movement?.id }); const receivedTotal = quantity(Number(orderItem.received_quantity || 0) + quantity(input.received_quantity)); const acceptedTotal = quantity(Number(orderItem.accepted_quantity || 0) + quantity(input.accepted_quantity)); const rejectedTotal = quantity(Number(orderItem.rejected_quantity || 0) + quantity(input.rejected_quantity)); await db.PurchaseOrderItem.update(orderItem.id, { received_quantity: receivedTotal, accepted_quantity: acceptedTotal, rejected_quantity: rejectedTotal, line_status: receivedTotal >= quantity(orderItem.ordered_quantity) ? 'received' : 'partially_received' }); results.push({ goods_receipt_item_id: created.id, stock_movement_id: stockResult.movement?.id }); }
        const finalStatus = receiptStatus(lines.map((line: any) => ({ received: line.received_quantity, accepted: line.accepted_quantity, rejected: line.rejected_quantity }))); const allItems = await db.PurchaseOrderItem.filter({ purchase_order_id: order.id }, 'created_date', 1000); const complete = allItems.every((line: any) => Number(line.received_quantity || 0) >= Number(line.ordered_quantity || 0)); const updatedReceipt = await db.GoodsReceipt.update(receipt.id, { status: finalStatus }); await db.PurchaseOrder.update(order.id, { status: complete ? 'received' : 'partially_received' }); if (body.purchase_document_id) { const doc = await db.PurchaseDocument.get(body.purchase_document_id).catch(() => null); if (doc && doc.legal_entity_id === order.legal_entity_id) await db.PurchaseDocument.update(doc.id, { purchase_order_id: order.id, goods_receipt_ids: [...new Set([...(doc.goods_receipt_ids || []), receipt.id])], status: complete ? 'received_complete' : 'partially_received' }); }
        await audit(db, principal, { action: 'approve', entity_type: 'goods_receipt', entity_id: receipt.id, item_label: receipt.receipt_number, amount: order.total, reason: justification(body.reason), legal_entity_id: order.legal_entity_id, unit_id: order.unit_id, request_id: requestId, after_data: { status: finalStatus, line_count: results.length, purchase_order_status: complete ? 'received' : 'partially_received' } }); return Response.json({ goods_receipt: updatedReceipt, results, request_id: requestId }, { status: 201 });
      } catch (error: any) { await db.GoodsReceipt.update(receipt.id, { status: 'quality_hold', divergence_summary: 'Falha parcial no recebimento; reparo administrativo obrigatório.' }).catch(() => null); await db.RepairTask.create({ legal_entity_id: order.legal_entity_id, unit_id: order.unit_id, domain: 'inventory', entity_type: 'goods_receipt', entity_id: receipt.id, title: 'Reparar recebimento de mercadorias', description: 'O recebimento falhou após iniciar lançamentos e não deve ser repetido automaticamente.', severity: 'critical', status: 'open', required_permission: 'repairs.manage', checkpoints: results.map((item: any) => item.goods_receipt_item_id), context_snapshot: { purchase_order_id: order.id, safe_error_code: clean(error?.message, 120) }, metadata: {} }).catch(() => null); throw Object.assign(new Error('receipt_partial_failure_requires_repair'), { status: 409 }); }
    }

    return Response.json({ error: 'unsupported_action', request_id: requestId }, { status: 400 });
  } catch (error: any) {
    if (error?.name === 'SecurityError') return securityErrorResponse(error);
    const status = Number(error?.status || (['reason_required', 'invalid_quantity', 'invalid_amount', 'receipt_quantities_exceed_received', 'receipt_items_required'].includes(error?.message) ? 422 : 500)); return Response.json({ error: clean(error?.message || 'procurement_operation_failed', 120), request_id: requestId }, { status });
  }
}
